CatalogPageBlockViews:
    type: enum
    config:
        values:
            default:
                value: '@ibexadesign/product_catalog/page_builder/blocks/catalog.html.twig'
                description: 'Default block layout'
