IbexaNewsPageBlockViews:
    type: enum
    config:
        values:
            default:
                value: '@ibexadesign/dashboard/blocks/ibexa_news.html.twig'
                description: 'Default block layout'
