MyContentPageBlockViews:
    type: enum
    config:
        values:
            default:
                value: '@ibexadesign/dashboard/blocks/my_content.html.twig'
                description: 'Default view'
