ReviewQueuePageBlockViews:
    type: enum
    config:
        values:
            default:
                value: '@ibexadesign/dashboard/blocks/review_queue.html.twig'
                description: 'Default view'
