<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R9jY3mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._R9jY3m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._R9jY3m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'view' => ['privates', '.errored..service_locator._R9jY3m.Ibexa\\User\\View\\UserSettings\\UpdateView', NULL, 'Cannot autowire service ".service_locator._R9jY3m": it references class "Ibexa\\User\\View\\UserSettings\\UpdateView" but no such service exists.'],
        ], [
            'view' => 'Ibexa\\User\\View\\UserSettings\\UpdateView',
        ]);
    }
}
