<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EMzehZJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eMzehZJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eMzehZJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'company' => ['privates', '.errored..service_locator.eMzehZJ.Ibexa\\Contracts\\CorporateAccount\\Values\\Company', NULL, 'Cannot autowire service ".service_locator.eMzehZJ": it references class "Ibexa\\Contracts\\CorporateAccount\\Values\\Company" but no such service exists.'],
            'companyUpdateStruct' => ['privates', '.errored..service_locator.eMzehZJ.Ibexa\\CorporateAccount\\REST\\Value\\CompanyUpdateStruct', NULL, 'Cannot autowire service ".service_locator.eMzehZJ": it references class "Ibexa\\CorporateAccount\\REST\\Value\\CompanyUpdateStruct" but no such service exists.'],
        ], [
            'company' => 'Ibexa\\Contracts\\CorporateAccount\\Values\\Company',
            'companyUpdateStruct' => 'Ibexa\\CorporateAccount\\REST\\Value\\CompanyUpdateStruct',
        ]);
    }
}
