<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bs3uVGzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bs3uVGz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bs3uVGz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'objectStateGroup' => ['privates', '.errored..service_locator.Bs3uVGz.Ibexa\\Contracts\\Core\\Repository\\Values\\ObjectState\\ObjectStateGroup', NULL, 'Cannot autowire service ".service_locator.Bs3uVGz": it references class "Ibexa\\Contracts\\Core\\Repository\\Values\\ObjectState\\ObjectStateGroup" but no such service exists.'],
        ], [
            'objectStateGroup' => 'Ibexa\\Contracts\\Core\\Repository\\Values\\ObjectState\\ObjectStateGroup',
        ]);
    }
}
