<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ChXQBH9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ChXQBH9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ChXQBH9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'role' => ['privates', '.errored..service_locator.ChXQBH9.Ibexa\\Contracts\\Core\\Repository\\Values\\User\\Role', NULL, 'Cannot autowire service ".service_locator.ChXQBH9": it references class "Ibexa\\Contracts\\Core\\Repository\\Values\\User\\Role" but no such service exists.'],
        ], [
            'role' => 'Ibexa\\Contracts\\Core\\Repository\\Values\\User\\Role',
        ]);
    }
}
