<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EOSKFHPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EOSKFHP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EOSKFHP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customerGroup' => ['privates', '.errored..service_locator.EOSKFHP.Ibexa\\ProductCatalog\\Local\\Repository\\Values\\CustomerGroup', NULL, 'Cannot autowire service ".service_locator.EOSKFHP": it references class "Ibexa\\ProductCatalog\\Local\\Repository\\Values\\CustomerGroup" but no such service exists.'],
        ], [
            'customerGroup' => 'Ibexa\\ProductCatalog\\Local\\Repository\\Values\\CustomerGroup',
        ]);
    }
}
