<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetViewControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\Connector\Dam\Controller\AssetViewController' shared autowired service.
     *
     * @return \Ibexa\Bundle\Connector\Dam\Controller\AssetViewController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/connector-dam/src/bundle/Controller/AssetViewController.php';

        $container->services['Ibexa\\Bundle\\Connector\\Dam\\Controller\\AssetViewController'] = $instance = new \Ibexa\Bundle\Connector\Dam\Controller\AssetViewController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Ibexa\\Bundle\\Connector\\Dam\\Controller\\AssetViewController', $container));

        return $instance;
    }
}
