<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvailableDashboardTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\Dashboard\Form\Type\AvailableDashboardType' shared autowired service.
     *
     * @return \Ibexa\Bundle\Dashboard\Form\Type\AvailableDashboardType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/dashboard/src/bundle/Form/Type/DashboardAbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/dashboard/src/bundle/Form/Type/AvailableDashboardType.php';

        $a = ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService());

        if (isset($container->privates['Ibexa\\Bundle\\Dashboard\\Form\\Type\\AvailableDashboardType'])) {
            return $container->privates['Ibexa\\Bundle\\Dashboard\\Form\\Type\\AvailableDashboardType'];
        }
        $b = ($container->services['ibexa.api.service.user_preference'] ?? $container->getIbexa_Api_Service_UserPreferenceService());

        if (isset($container->privates['Ibexa\\Bundle\\Dashboard\\Form\\Type\\AvailableDashboardType'])) {
            return $container->privates['Ibexa\\Bundle\\Dashboard\\Form\\Type\\AvailableDashboardType'];
        }

        return $container->privates['Ibexa\\Bundle\\Dashboard\\Form\\Type\\AvailableDashboardType'] = new \Ibexa\Bundle\Dashboard\Form\Type\AvailableDashboardType($a, ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()), $b);
    }
}
