<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationDetailsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\CorporateAccount\Controller\ApplicationDetailsController' shared autowired service.
     *
     * @return \Ibexa\Bundle\CorporateAccount\Controller\ApplicationDetailsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/bundle/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/bundle/Controller/ApplicationDetailsController.php';

        $container->services['Ibexa\\Bundle\\CorporateAccount\\Controller\\ApplicationDetailsController'] = $instance = new \Ibexa\Bundle\CorporateAccount\Controller\ApplicationDetailsController(($container->privates['Ibexa\\CorporateAccount\\Configuration\\CorporateAccount'] ?? $container->getCorporateAccountService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Ibexa\\Bundle\\CorporateAccount\\Controller\\ApplicationDetailsController', $container));

        return $instance;
    }
}
