<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aiXi3LU.Ibexa\Contracts\CorporateAccount\Values\Application' shared service.
     *
     * @return \Ibexa\Contracts\CorporateAccount\Values\Application
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.aiXi3LU": it references class "Ibexa\\Contracts\\CorporateAccount\\Values\\Application" but no such service exists.');
    }
}
