<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeUnitConstraintValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Measurement\ProductCatalog\Form\Attribute\AttributeUnitConstraintValidator' shared autowired service.
     *
     * @return \Ibexa\Measurement\ProductCatalog\Form\Attribute\AttributeUnitConstraintValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/measurement/src/lib/ProductCatalog/Form/Attribute/AttributeUnitConstraintValidator.php';

        return $container->privates['Ibexa\\Measurement\\ProductCatalog\\Form\\Attribute\\AttributeUnitConstraintValidator'] = new \Ibexa\Measurement\ProductCatalog\Form\Attribute\AttributeUnitConstraintValidator(($container->privates['Ibexa\\Measurement\\MeasurementTypeFactory'] ?? $container->getMeasurementTypeFactoryService()));
    }
}
