<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddSwitchLayoutToolEventSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\PageBuilder\Menu\Event\Subscriber\AddSwitchLayoutToolEventSubscriber' shared autowired service.
     *
     * @return \Ibexa\Bundle\PageBuilder\Menu\Event\Subscriber\AddSwitchLayoutToolEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/page-builder/src/bundle/Menu/Event/Subscriber/AddSwitchLayoutToolEventSubscriber.php';

        $a = ($container->services['Ibexa\\FieldTypePage\\ApplicationConfig\\Providers\\LayoutDefinitions'] ?? $container->load('getLayoutDefinitionsService'));

        if (isset($container->services['Ibexa\\Bundle\\PageBuilder\\Menu\\Event\\Subscriber\\AddSwitchLayoutToolEventSubscriber'])) {
            return $container->services['Ibexa\\Bundle\\PageBuilder\\Menu\\Event\\Subscriber\\AddSwitchLayoutToolEventSubscriber'];
        }

        return $container->services['Ibexa\\Bundle\\PageBuilder\\Menu\\Event\\Subscriber\\AddSwitchLayoutToolEventSubscriber'] = new \Ibexa\Bundle\PageBuilder\Menu\Event\Subscriber\AddSwitchLayoutToolEventSubscriber($a);
    }
}
