<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeCreateStepExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ProductCatalog\Migrations\Attribute\AttributeCreateStepExecutor' shared autowired service.
     *
     * @return \Ibexa\ProductCatalog\Migrations\Attribute\AttributeCreateStepExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/StepExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/UserContextAwareStepExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/service-contracts/ServiceSubscriberTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/UserContextAwareStepExecutorTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/contracts/StepExecutor/AbstractStepExecutor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/Migrations/Attribute/AttributeCreateStepExecutor.php';

        $container->privates['Ibexa\\ProductCatalog\\Migrations\\Attribute\\AttributeCreateStepExecutor'] = $instance = new \Ibexa\ProductCatalog\Migrations\Attribute\AttributeCreateStepExecutor(($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\Event\\AttributeDefinitionService'] ?? $container->load('getAttributeDefinitionServiceService')), ($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\AttributeTypeService'] ?? $container->getAttributeTypeServiceService()), ($container->privates['Ibexa\\ProductCatalog\\Dispatcher\\AttributeGroupServiceDispatcher'] ?? $container->getAttributeGroupServiceDispatcherService()));

        $instance->setContainer(($container->privates['.service_locator.A.yU1Hk'] ?? $container->load('get_ServiceLocator_A_YU1HkService'))->withContext('Ibexa\\ProductCatalog\\Migrations\\Attribute\\AttributeCreateStepExecutor', $container));

        return $instance;
    }
}
