<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeRichTextTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\FieldTypePage\Form\Type\BlockAttribute\AttributeRichTextType' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\Form\Type\BlockAttribute\AttributeRichTextType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/Form/Type/BlockAttribute/AttributeRichTextType.php';

        return $container->privates['Ibexa\\FieldTypePage\\Form\\Type\\BlockAttribute\\AttributeRichTextType'] = new \Ibexa\FieldTypePage\Form\Type\BlockAttribute\AttributeRichTextType();
    }
}
