<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeFilterDefinitionProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ProductCatalog\Local\Repository\CatalogFilter\DefinitionProvider\AttributeFilterDefinitionProvider' shared autowired service.
     *
     * @return \Ibexa\ProductCatalog\Local\Repository\CatalogFilter\DefinitionProvider\AttributeFilterDefinitionProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/contracts/CatalogFilters/FilterDefinitionProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/Local/Repository/CatalogFilter/DefinitionProvider/AttributeFilterDefinitionProvider.php';

        $a = ($container->privates['Ibexa\\ProductCatalog\\Dispatcher\\AttributeDefinitionServiceDispatcher'] ?? $container->getAttributeDefinitionServiceDispatcherService());

        if (isset($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\CatalogFilter\\DefinitionProvider\\AttributeFilterDefinitionProvider'])) {
            return $container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\CatalogFilter\\DefinitionProvider\\AttributeFilterDefinitionProvider'];
        }

        return $container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\CatalogFilter\\DefinitionProvider\\AttributeFilterDefinitionProvider'] = new \Ibexa\ProductCatalog\Local\Repository\CatalogFilter\DefinitionProvider\AttributeFilterDefinitionProvider($a, new RewindableGenerator(function () use ($container) {
            yield 'checkbox' => ($container->privates['ibexa.product_catalog.catalog_filter.attribute_filter_definition_factory.checkbox'] ?? ($container->privates['ibexa.product_catalog.catalog_filter.attribute_filter_definition_factory.checkbox'] = new \Ibexa\ProductCatalog\Local\Repository\CatalogFilter\DefinitionProvider\Attribute\FilterDefinitionFactory('Ibexa\\Contracts\\ProductCatalog\\Values\\Product\\Query\\Criterion\\CheckboxAttribute')));
            yield 'float' => ($container->privates['ibexa.product_catalog.catalog_filter.attribute_filter_definition_factory.float'] ?? ($container->privates['ibexa.product_catalog.catalog_filter.attribute_filter_definition_factory.float'] = new \Ibexa\ProductCatalog\Local\Repository\CatalogFilter\DefinitionProvider\Attribute\FilterDefinitionFactory('Ibexa\\Contracts\\ProductCatalog\\Values\\Product\\Query\\Criterion\\FloatAttributeRange')));
            yield 'integer' => ($container->privates['ibexa.product_catalog.catalog_filter.attribute_filter_definition_factory.integer'] ?? ($container->privates['ibexa.product_catalog.catalog_filter.attribute_filter_definition_factory.integer'] = new \Ibexa\ProductCatalog\Local\Repository\CatalogFilter\DefinitionProvider\Attribute\FilterDefinitionFactory('Ibexa\\Contracts\\ProductCatalog\\Values\\Product\\Query\\Criterion\\IntegerAttributeRange')));
            yield 'selection' => ($container->privates['ibexa.product_catalog.catalog_filter.attribute_filter_definition_factory.selection'] ?? ($container->privates['ibexa.product_catalog.catalog_filter.attribute_filter_definition_factory.selection'] = new \Ibexa\ProductCatalog\Local\Repository\CatalogFilter\DefinitionProvider\Attribute\FilterDefinitionFactory('Ibexa\\Contracts\\ProductCatalog\\Values\\Product\\Query\\Criterion\\SelectionAttribute')));
            yield 'color' => ($container->privates['ibexa.product_catalog.catalog_filter.attribute_filter_definition_factory.color'] ?? ($container->privates['ibexa.product_catalog.catalog_filter.attribute_filter_definition_factory.color'] = new \Ibexa\ProductCatalog\Local\Repository\CatalogFilter\DefinitionProvider\Attribute\FilterDefinitionFactory('Ibexa\\Contracts\\ProductCatalog\\Values\\Product\\Query\\Criterion\\ColorAttribute')));
        }, 5));
    }
}
