<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationListViewSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\CorporateAccount\EventSubscriber\ApplicationListViewSubscriber' shared autowired service.
     *
     * @return \Ibexa\Bundle\CorporateAccount\EventSubscriber\ApplicationListViewSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/bundle/EventSubscriber/AbstractViewSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/bundle/EventSubscriber/ApplicationListViewSubscriber.php';

        $a = ($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService());

        if (isset($container->privates['Ibexa\\Bundle\\CorporateAccount\\EventSubscriber\\ApplicationListViewSubscriber'])) {
            return $container->privates['Ibexa\\Bundle\\CorporateAccount\\EventSubscriber\\ApplicationListViewSubscriber'];
        }
        $b = ($container->privates['Ibexa\\AdminUi\\Form\\Factory\\FormFactory'] ?? $container->getFormFactory2Service());

        if (isset($container->privates['Ibexa\\Bundle\\CorporateAccount\\EventSubscriber\\ApplicationListViewSubscriber'])) {
            return $container->privates['Ibexa\\Bundle\\CorporateAccount\\EventSubscriber\\ApplicationListViewSubscriber'];
        }

        return $container->privates['Ibexa\\Bundle\\CorporateAccount\\EventSubscriber\\ApplicationListViewSubscriber'] = new \Ibexa\Bundle\CorporateAccount\EventSubscriber\ApplicationListViewSubscriber(($container->privates['Ibexa\\Core\\MVC\\Symfony\\SiteAccess\\SiteAccessService'] ?? $container->getSiteAccessServiceService()), $a, $b);
    }
}
