<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetsTabService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ProductCatalog\Tab\Product\AssetsTab' shared autowired service.
     *
     * @return \Ibexa\ProductCatalog\Tab\Product\AssetsTab
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->privates['Ibexa\\ProductCatalog\\Tab\\Product\\AssetsTab'] = $container->createProxy('AssetsTab_2406885', function () use ($container) {
                return \AssetsTab_2406885::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/TabInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/AbstractTab.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/AbstractEventDispatchingTab.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/OrderedTabInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/ConditionalTabInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/Tab/Product/AssetsTab.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/UI/AssetGroup/AssetGroupCollectionFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/UI/AssetGroup/AssetGroupCollectionFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/lib/ConfigResolver/MaxUploadSize.php';

        return new \Ibexa\ProductCatalog\Tab\Product\AssetsTab(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['Ibexa\\ProductCatalog\\Dispatcher\\AssetsServiceDispatcher'] ?? $container->load('getAssetsServiceDispatcherService')), ($container->services['.container.private.form.factory'] ?? $container->get_Container_Private_Form_FactoryService()), ($container->services['router'] ?? $container->getRouterService()), new \Ibexa\Bundle\ProductCatalog\UI\AssetGroup\AssetGroupCollectionFactory(($container->privates['Ibexa\\ProductCatalog\\Dispatcher\\AttributeDefinitionServiceDispatcher'] ?? $container->getAttributeDefinitionServiceDispatcherService()), ($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\Attribute\\ValueFormatterDispatcher'] ?? $container->getValueFormatterDispatcherService())), ($container->privates['Ibexa\\ContentForms\\ConfigResolver\\MaxUploadSize'] ?? ($container->privates['Ibexa\\ContentForms\\ConfigResolver\\MaxUploadSize'] = new \Ibexa\ContentForms\ConfigResolver\MaxUploadSize())));
    }
}
