<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetSourceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IlSsMcA.Ibexa\Contracts\Connector\Dam\AssetSource' shared service.
     *
     * @return \Ibexa\Contracts\Connector\Dam\AssetSource
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.IlSsMcA": it references class "Ibexa\\Contracts\\Connector\\Dam\\AssetSource" but no such service exists.');
    }
}
