<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssignRoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Migration\StepExecutor\ActionExecutor\UserGroup\AssignRole' shared autowired service.
     *
     * @return \Ibexa\Migration\StepExecutor\ActionExecutor\UserGroup\AssignRole
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ActionExecutor/ExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ActionExecutor/UserGroup/AssignRole.php';

        return $container->privates['Ibexa\\Migration\\StepExecutor\\ActionExecutor\\UserGroup\\AssignRole'] = new \Ibexa\Migration\StepExecutor\ActionExecutor\UserGroup\AssignRole(($container->services['ibexa.api.service.role'] ?? $container->getIbexa_Api_Service_RoleService()));
    }
}
