<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeDefinitionUsedRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\ProductCatalog\Twig\Test\AttributeDefinitionUsedRuntime' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Twig\Test\AttributeDefinitionUsedRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Twig/Test/AttributeDefinitionUsedRuntime.php';

        $a = ($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\Event\\AttributeDefinitionService'] ?? $container->load('getAttributeDefinitionServiceService'));

        if (isset($container->privates['Ibexa\\Bundle\\ProductCatalog\\Twig\\Test\\AttributeDefinitionUsedRuntime'])) {
            return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Twig\\Test\\AttributeDefinitionUsedRuntime'];
        }

        return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Twig\\Test\\AttributeDefinitionUsedRuntime'] = new \Ibexa\Bundle\ProductCatalog\Twig\Test\AttributeDefinitionUsedRuntime($a);
    }
}
