<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBase64ControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\ImageEditor\Controller\Base64Controller' shared autowired service.
     *
     * @return \Ibexa\Bundle\ImageEditor\Controller\Base64Controller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/image-editor/src/bundle/Controller/Base64Controller.php';

        return $container->services['Ibexa\\Bundle\\ImageEditor\\Controller\\Base64Controller'] = new \Ibexa\Bundle\ImageEditor\Controller\Base64Controller(($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService()), ($container->privates['Ibexa\\Core\\FieldType\\ImageAsset\\AssetMapper'] ?? $container->getAssetMapperService()));
    }
}
