<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockDefinitionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FieldTypePage\ApplicationConfig\Providers\BlockDefinitions' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\ApplicationConfig\Providers\BlockDefinitions
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/ApplicationConfig/Providers/BlockDefinitionsInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/ApplicationConfig/Providers/BlockDefinitions.php';

        $a = ($container->services['Ibexa\\FieldTypePage\\FieldType\\LandingPage\\Converter\\BlockDefinitionConverter'] ?? $container->load('getBlockDefinitionConverterService'));

        if (isset($container->services['Ibexa\\FieldTypePage\\ApplicationConfig\\Providers\\BlockDefinitions'])) {
            return $container->services['Ibexa\\FieldTypePage\\ApplicationConfig\\Providers\\BlockDefinitions'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['Ibexa\\FieldTypePage\\ApplicationConfig\\Providers\\BlockDefinitions'])) {
            return $container->services['Ibexa\\FieldTypePage\\ApplicationConfig\\Providers\\BlockDefinitions'];
        }

        return $container->services['Ibexa\\FieldTypePage\\ApplicationConfig\\Providers\\BlockDefinitions'] = new \Ibexa\FieldTypePage\ApplicationConfig\Providers\BlockDefinitions($a, $b);
    }
}
