<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockVisibilityEntryBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FieldTypePage\Calendar\BlockVisibilityEntryBuilder' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\Calendar\BlockVisibilityEntryBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/Calendar/BlockVisibilityEntryBuilder.php';

        $a = ($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService());

        if (isset($container->services['Ibexa\\FieldTypePage\\Calendar\\BlockVisibilityEntryBuilder'])) {
            return $container->services['Ibexa\\FieldTypePage\\Calendar\\BlockVisibilityEntryBuilder'];
        }
        $b = ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService());

        if (isset($container->services['Ibexa\\FieldTypePage\\Calendar\\BlockVisibilityEntryBuilder'])) {
            return $container->services['Ibexa\\FieldTypePage\\Calendar\\BlockVisibilityEntryBuilder'];
        }

        return $container->services['Ibexa\\FieldTypePage\\Calendar\\BlockVisibilityEntryBuilder'] = new \Ibexa\FieldTypePage\Calendar\BlockVisibilityEntryBuilder($a, $b, ($container->services['ibexa.api.service.language'] ?? $container->getIbexa_Api_Service_LanguageService()));
    }
}
