<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseDataToStructTransformer3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\ProductCatalog\Form\DataMapper\ProductPrice\Update\BaseDataToStructTransformer' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Form\DataMapper\ProductPrice\Update\BaseDataToStructTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Form/DataMapper/ProductPrice/DataToStructTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Form/DataMapper/ProductPrice/Update/BaseDataToStructTransformer.php';

        return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\DataMapper\\ProductPrice\\Update\\BaseDataToStructTransformer'] = new \Ibexa\Bundle\ProductCatalog\Form\DataMapper\ProductPrice\Update\BaseDataToStructTransformer(($container->privates['Ibexa\\ProductCatalog\\Money\\DecimalMoneyFactory'] ?? $container->getDecimalMoneyFactoryService()));
    }
}
