<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockDefinitionConverterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FieldTypePage\FieldType\LandingPage\Converter\BlockDefinitionConverter' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\FieldType\LandingPage\Converter\BlockDefinitionConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/FieldType/LandingPage/Converter/BlockDefinitionConverter.php';

        $a = ($container->services['Ibexa\\FieldTypePage\\FieldType\\Page\\Block\\Definition\\CachedBlockDefinitionFactory'] ?? $container->getCachedBlockDefinitionFactoryService());

        if (isset($container->services['Ibexa\\FieldTypePage\\FieldType\\LandingPage\\Converter\\BlockDefinitionConverter'])) {
            return $container->services['Ibexa\\FieldTypePage\\FieldType\\LandingPage\\Converter\\BlockDefinitionConverter'];
        }

        return $container->services['Ibexa\\FieldTypePage\\FieldType\\LandingPage\\Converter\\BlockDefinitionConverter'] = new \Ibexa\FieldTypePage\FieldType\LandingPage\Converter\BlockDefinitionConverter($a);
    }
}
