<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockRevealEventTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FieldTypePage\Calendar\BlockRevealEventType' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\Calendar\BlockRevealEventType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/calendar/src/contracts/EventType/EventTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/Calendar/BlockRevealEventType.php';

        return $container->services['Ibexa\\FieldTypePage\\Calendar\\BlockRevealEventType'] = new \Ibexa\FieldTypePage\Calendar\BlockRevealEventType(new RewindableGenerator(function () use ($container) {
            return new \EmptyIterator();
        }, 0), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()));
    }
}
