<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\FieldTypePage\Controller\BlockController' shared autowired service.
     *
     * @return \Ibexa\Bundle\FieldTypePage\Controller\BlockController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/bundle/Controller/BlockController.php';

        $container->services['Ibexa\\Bundle\\FieldTypePage\\Controller\\BlockController'] = $instance = new \Ibexa\Bundle\FieldTypePage\Controller\BlockController(($container->privates['Ibexa\\FieldTypePage\\FieldType\\Page\\Service\\BlockService'] ?? $container->getBlockServiceService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['Ibexa\\FieldTypePage\\FieldType\\Page\\FieldDefinitionLocator'] ?? $container->getFieldDefinitionLocatorService()), ($container->services['Ibexa\\FieldTypePage\\FieldType\\Page\\Block\\Definition\\CachedBlockDefinitionFactory'] ?? $container->getCachedBlockDefinitionFactoryService()));

        $instance->setContainer(($container->privates['.service_locator.GS60sXn'] ?? $container->load('get_ServiceLocator_GS60sXnService'))->withContext('Ibexa\\Bundle\\FieldTypePage\\Controller\\BlockController', $container));

        return $instance;
    }
}
