<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigured2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ContentForms\Content\View\Provider\ContentEditView\Configured' shared autowired service.
     *
     * @return \Ibexa\ContentForms\Content\View\Provider\ContentEditView\Configured
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/View/ViewProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/lib/Content/View/Provider/ContentEditView/Configured.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/Matcher/MatcherFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/Matcher/DynamicallyConfiguredMatcherFactoryDecorator.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/Matcher/ConfigurableMatcherFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/Matcher/ClassNameMatcherFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/Matcher/ServiceAwareMatcherFactory.php';

        $a = ($container->privates['Ibexa\\Bundle\\Core\\Matcher\\ViewMatcherRegistry'] ?? $container->load('getViewMatcherRegistryService'));

        if (isset($container->privates['Ibexa\\ContentForms\\Content\\View\\Provider\\ContentEditView\\Configured'])) {
            return $container->privates['Ibexa\\ContentForms\\Content\\View\\Provider\\ContentEditView\\Configured'];
        }
        $b = ($container->services['ibexa.api.repository'] ?? $container->getIbexa_Api_RepositoryService());

        if (isset($container->privates['Ibexa\\ContentForms\\Content\\View\\Provider\\ContentEditView\\Configured'])) {
            return $container->privates['Ibexa\\ContentForms\\Content\\View\\Provider\\ContentEditView\\Configured'];
        }

        return $container->privates['Ibexa\\ContentForms\\Content\\View\\Provider\\ContentEditView\\Configured'] = new \Ibexa\ContentForms\Content\View\Provider\ContentEditView\Configured(new \Ibexa\Core\MVC\Symfony\Matcher\DynamicallyConfiguredMatcherFactoryDecorator(new \Ibexa\Bundle\Core\Matcher\ServiceAwareMatcherFactory($a, $b, 'Ibexa\\Core\\MVC\\Symfony\\Matcher\\ContentBased'), ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()), 'content_edit_view'));
    }
}
