<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentSidebarMenuSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Workflow\Event\Subscriber\ContentSidebarMenuSubscriber' shared autowired service.
     *
     * @return \Ibexa\Workflow\Event\Subscriber\ContentSidebarMenuSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/workflow/src/lib/Event/Subscriber/AbstractMenuSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/workflow/src/lib/Event/Subscriber/ContentSidebarMenuSubscriber.php';

        $a = ($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService'));

        if (isset($container->privates['Ibexa\\Workflow\\Event\\Subscriber\\ContentSidebarMenuSubscriber'])) {
            return $container->privates['Ibexa\\Workflow\\Event\\Subscriber\\ContentSidebarMenuSubscriber'];
        }
        $b = ($container->privates['Ibexa\\Workflow\\Registry\\WorkflowRegistry'] ?? $container->getWorkflowRegistryService());

        if (isset($container->privates['Ibexa\\Workflow\\Event\\Subscriber\\ContentSidebarMenuSubscriber'])) {
            return $container->privates['Ibexa\\Workflow\\Event\\Subscriber\\ContentSidebarMenuSubscriber'];
        }
        $c = ($container->privates['Ibexa\\Workflow\\Registry\\WorkflowDefinitionMetadataRegistry'] ?? $container->getWorkflowDefinitionMetadataRegistryService());

        if (isset($container->privates['Ibexa\\Workflow\\Event\\Subscriber\\ContentSidebarMenuSubscriber'])) {
            return $container->privates['Ibexa\\Workflow\\Event\\Subscriber\\ContentSidebarMenuSubscriber'];
        }
        $d = ($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService());

        if (isset($container->privates['Ibexa\\Workflow\\Event\\Subscriber\\ContentSidebarMenuSubscriber'])) {
            return $container->privates['Ibexa\\Workflow\\Event\\Subscriber\\ContentSidebarMenuSubscriber'];
        }

        return $container->privates['Ibexa\\Workflow\\Event\\Subscriber\\ContentSidebarMenuSubscriber'] = new \Ibexa\Workflow\Event\Subscriber\ContentSidebarMenuSubscriber($a, $b, $c, $d);
    }
}
