<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCurrencyReferenceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\ProductCatalog\Form\Type\Currency\CurrencyReferenceType' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Form\Type\Currency\CurrencyReferenceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Form/Type/Currency/CurrencyReferenceType.php';

        $a = ($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\Event\\CurrencyService'] ?? $container->getCurrencyServiceService());

        if (isset($container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\Type\\Currency\\CurrencyReferenceType'])) {
            return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\Type\\Currency\\CurrencyReferenceType'];
        }

        return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\Type\\Currency\\CurrencyReferenceType'] = new \Ibexa\Bundle\ProductCatalog\Form\Type\Currency\CurrencyReferenceType($a);
    }
}
