<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountryFieldTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ContentForms\Form\Type\FieldType\CountryFieldType' shared autowired service.
     *
     * @return \Ibexa\ContentForms\Form\Type\FieldType\CountryFieldType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/lib/Form/Type/FieldType/CountryFieldType.php';

        return $container->privates['Ibexa\\ContentForms\\Form\\Type\\FieldType\\CountryFieldType'] = new \Ibexa\ContentForms\Form\Type\FieldType\CountryFieldType($container->parameters['ibexa.field_type.country.data']);
    }
}
