<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyListControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\CorporateAccount\Controller\CompanyListController' shared autowired service.
     *
     * @return \Ibexa\Bundle\CorporateAccount\Controller\CompanyListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/bundle/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/bundle/Controller/CompanyListController.php';

        $container->services['Ibexa\\Bundle\\CorporateAccount\\Controller\\CompanyListController'] = $instance = new \Ibexa\Bundle\CorporateAccount\Controller\CompanyListController(($container->privates['Ibexa\\CorporateAccount\\Configuration\\CorporateAccount'] ?? $container->getCorporateAccountService()), ($container->privates['Ibexa\\CorporateAccount\\Event\\CompanyService'] ?? $container->getCompanyServiceService()), ($container->privates['Ibexa\\CorporateAccount\\Form\\CompanyFormFactory'] ?? $container->load('getCompanyFormFactoryService')), ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()), ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Ibexa\\Bundle\\CorporateAccount\\Controller\\CompanyListController', $container));

        return $instance;
    }
}
