<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreate5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Migration\Generator\ObjectStateGroup\StepBuilder\Create' shared autowired service.
     *
     * @return \Ibexa\Migration\Generator\ObjectStateGroup\StepBuilder\Create
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Generator/StepBuilder/StepBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Generator/ObjectStateGroup/StepBuilder/Create.php';

        return $container->privates['Ibexa\\Migration\\Generator\\ObjectStateGroup\\StepBuilder\\Create'] = new \Ibexa\Migration\Generator\ObjectStateGroup\StepBuilder\Create(($container->services['ibexa.api.service.object_state'] ?? $container->getIbexa_Api_Service_ObjectStateService()));
    }
}
