<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentTypeGroup2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Q1KPLec.Ibexa\Contracts\Core\Repository\Values\ContentType\ContentTypeGroup' shared service.
     *
     * @return \Ibexa\Contracts\Core\Repository\Values\ContentType\ContentTypeGroup
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Q1KPLec": it references class "Ibexa\\Contracts\\Core\\Repository\\Values\\ContentType\\ContentTypeGroup" but no such service exists.');
    }
}
