<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentTypeThumbnailStrategyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\AdminUi\Strategy\ContentTypeThumbnailStrategy' shared autowired service.
     *
     * @return \Ibexa\AdminUi\Strategy\ContentTypeThumbnailStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Strategy/ContentTypeThumbnailStrategy.php';

        return $container->privates['Ibexa\\AdminUi\\Strategy\\ContentTypeThumbnailStrategy'] = new \Ibexa\AdminUi\Strategy\ContentTypeThumbnailStrategy(($container->privates['Ibexa\\AdminUi\\UI\\Service\\ContentTypeIconResolver'] ?? $container->getContentTypeIconResolverService()));
    }
}
