<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComparable2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\VersionComparison\FieldType\ImageAsset\Comparable' shared autowired service.
     *
     * @return \Ibexa\VersionComparison\FieldType\ImageAsset\Comparable
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/version-comparison/src/contracts/FieldType/Comparable.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/version-comparison/src/lib/FieldType/ImageAsset/Comparable.php';

        return $container->privates['Ibexa\\VersionComparison\\FieldType\\ImageAsset\\Comparable'] = new \Ibexa\VersionComparison\FieldType\ImageAsset\Comparable(($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService()), ($container->privates['Ibexa\\Core\\FieldType\\ImageAsset\\AssetMapper'] ?? $container->getAssetMapperService()), ($container->privates['Ibexa\\Core\\FieldType\\Image\\Type'] ?? $container->getType20Service()));
    }
}
