<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_AppClearerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cache.app_clearer' shared service.
     *
     * @return \Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/CacheClearer/CacheClearerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/CacheClearer/Psr6CacheClearer.php';

        return $container->services['cache.app_clearer'] = new \Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer(['cache.tagaware.filesystem' => ($container->services['cache.tagaware.filesystem'] ?? $container->getCache_Tagaware_FilesystemService()), 'cache.app' => ($container->services['cache.app'] ?? $container->getCache_AppService()), 'cache.rate_limiter' => ($container->services['cache.rate_limiter'] ?? $container->getCache_RateLimiterService()), 'site_factory_pool' => ($container->privates['.site_factory_pool.inner'] ?? $container->get_SiteFactoryPool_InnerService())]);
    }
}
