<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreate12Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Segmentation\Generator\SegmentGroup\StepBuilder\Create' shared autowired service.
     *
     * @return \Ibexa\Segmentation\Generator\SegmentGroup\StepBuilder\Create
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Generator/StepBuilder/StepBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/segmentation/src/lib/Generator/SegmentGroup/StepBuilder/Create.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Generator/Reference/AbstractReferenceGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/segmentation/src/lib/Generator/Reference/SegmentGroupGenerator.php';

        return $container->privates['Ibexa\\Segmentation\\Generator\\SegmentGroup\\StepBuilder\\Create'] = new \Ibexa\Segmentation\Generator\SegmentGroup\StepBuilder\Create(new \Ibexa\Segmentation\Generator\Reference\SegmentGroupGenerator());
    }
}
