<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentEditController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\ContentForms\Controller\ContentEditController' shared service.
     *
     * @return \Ibexa\Bundle\ContentForms\Controller\ContentEditController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/bundle/Controller/ContentEditController.php';

        $container->services['Ibexa\\Bundle\\ContentForms\\Controller\\ContentEditController'] = $instance = new \Ibexa\Bundle\ContentForms\Controller\ContentEditController(($container->services['ibexa.api.service.content_type'] ?? $container->getIbexa_Api_Service_ContentTypeService()), ($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService()), ($container->privates['Ibexa\\ContentForms\\Form\\ActionDispatcher\\ContentDispatcher'] ?? $container->load('getContentDispatcherService')));

        $instance->setContainer($container);

        return $instance;
    }
}
