<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaptchaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\FormBuilder\Controller\CaptchaController' shared autowired service.
     *
     * @return \Ibexa\Bundle\FormBuilder\Controller\CaptchaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/bundle/Controller/CaptchaController.php';

        $container->services['Ibexa\\Bundle\\FormBuilder\\Controller\\CaptchaController'] = $instance = new \Ibexa\Bundle\FormBuilder\Controller\CaptchaController($container->parameters['gregwar_captcha.config'], ($container->services['gregwar_captcha.generator'] ?? $container->load('getGregwarCaptcha_GeneratorService')));

        $instance->setContainer($container);

        return $instance;
    }
}
