<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentEventsSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FieldTypePage\Event\Subscriber\CachePurge\ContentEventsSubscriber' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\Event\Subscriber\CachePurge\ContentEventsSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/http-cache/src/lib/EventSubscriber/CachePurge/AbstractSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/Event/Subscriber/CachePurge/ContentEventsSubscriber.php';

        $a = ($container->privates['Ibexa\\Core\\Persistence\\Cache\\LocationHandler'] ?? $container->getLocationHandler2Service());

        if (isset($container->services['Ibexa\\FieldTypePage\\Event\\Subscriber\\CachePurge\\ContentEventsSubscriber'])) {
            return $container->services['Ibexa\\FieldTypePage\\Event\\Subscriber\\CachePurge\\ContentEventsSubscriber'];
        }
        $b = ($container->privates['Ibexa\\Core\\Persistence\\Cache\\URLHandler'] ?? $container->getURLHandlerService());

        if (isset($container->services['Ibexa\\FieldTypePage\\Event\\Subscriber\\CachePurge\\ContentEventsSubscriber'])) {
            return $container->services['Ibexa\\FieldTypePage\\Event\\Subscriber\\CachePurge\\ContentEventsSubscriber'];
        }

        return $container->services['Ibexa\\FieldTypePage\\Event\\Subscriber\\CachePurge\\ContentEventsSubscriber'] = new \Ibexa\FieldTypePage\Event\Subscriber\CachePurge\ContentEventsSubscriber(($container->privates['Ibexa\\HttpCache\\PurgeClient\\RepositoryPrefixDecorator'] ?? $container->getRepositoryPrefixDecoratorService()), $a, $b, $container->getEnv('default:ibexa.http_cache.translation_aware.enabled.default_value:bool:HTTPCACHE_TRANSLATION_AWARE_ENABLED'));
    }
}
