<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyFormFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\CorporateAccount\Form\CompanyFormFactory' shared autowired service.
     *
     * @return \Ibexa\CorporateAccount\Form\CompanyFormFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/lib/Form/ContentFormFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/lib/Form/CompanyFormFactory.php';

        $a = ($container->services['.container.private.form.factory'] ?? $container->get_Container_Private_Form_FactoryService());

        if (isset($container->privates['Ibexa\\CorporateAccount\\Form\\CompanyFormFactory'])) {
            return $container->privates['Ibexa\\CorporateAccount\\Form\\CompanyFormFactory'];
        }
        $b = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['Ibexa\\CorporateAccount\\Form\\CompanyFormFactory'])) {
            return $container->privates['Ibexa\\CorporateAccount\\Form\\CompanyFormFactory'];
        }
        $c = ($container->services['ibexa.api.service.content_type'] ?? $container->getIbexa_Api_Service_ContentTypeService());

        if (isset($container->privates['Ibexa\\CorporateAccount\\Form\\CompanyFormFactory'])) {
            return $container->privates['Ibexa\\CorporateAccount\\Form\\CompanyFormFactory'];
        }
        $d = ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService());

        if (isset($container->privates['Ibexa\\CorporateAccount\\Form\\CompanyFormFactory'])) {
            return $container->privates['Ibexa\\CorporateAccount\\Form\\CompanyFormFactory'];
        }

        return $container->privates['Ibexa\\CorporateAccount\\Form\\CompanyFormFactory'] = new \Ibexa\CorporateAccount\Form\CompanyFormFactory($a, ($container->privates['Ibexa\\CorporateAccount\\Configuration\\CorporateAccount'] ?? $container->getCorporateAccountService()), $b, $c, $d);
    }
}
