<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSiteSkeletonsContainerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Ibexa\Bundle\SiteFactory\Command\CreateSiteSkeletonsContainerCommand' shared autowired service.
     *
     * @return \Ibexa\Bundle\SiteFactory\Command\CreateSiteSkeletonsContainerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/site-factory/src/bundle/Command/CreateSiteSkeletonsContainerCommand.php';

        $container->services['console.command.public_alias.Ibexa\\Bundle\\SiteFactory\\Command\\CreateSiteSkeletonsContainerCommand'] = $instance = new \Ibexa\Bundle\SiteFactory\Command\CreateSiteSkeletonsContainerCommand(($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()), ($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService()), ($container->services['ibexa.api.service.content_type'] ?? $container->getIbexa_Api_Service_ContentTypeService()), ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService()), ($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService()), ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService()), ($container->services['ibexa.api.service.section'] ?? $container->getIbexa_Api_Service_SectionService()), ($container->services['ibexa.api.repository'] ?? $container->getIbexa_Api_RepositoryService()));

        $instance->addOption('siteaccess', NULL, 4, 'SiteAccess to use for operations. If not provided, default siteaccess will be used');

        return $instance;
    }
}
