<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurePersonalizationMenuListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Personalization\Event\Listener\ConfigurePersonalizationMenuListener' shared autowired service.
     *
     * @return \Ibexa\Personalization\Event\Listener\ConfigurePersonalizationMenuListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/personalization/src/lib/Event/Listener/ConfigurePersonalizationMenuListener.php';

        $a = ($container->services['Ibexa\\AdminUi\\Menu\\MenuItemFactory'] ?? $container->load('getMenuItemFactoryService'));

        if (isset($container->privates['Ibexa\\Personalization\\Event\\Listener\\ConfigurePersonalizationMenuListener'])) {
            return $container->privates['Ibexa\\Personalization\\Event\\Listener\\ConfigurePersonalizationMenuListener'];
        }
        $b = ($container->privates['Ibexa\\Personalization\\Service\\Setting\\DefaultSiteAccessSettingService'] ?? $container->load('getDefaultSiteAccessSettingServiceService'));

        if (isset($container->privates['Ibexa\\Personalization\\Event\\Listener\\ConfigurePersonalizationMenuListener'])) {
            return $container->privates['Ibexa\\Personalization\\Event\\Listener\\ConfigurePersonalizationMenuListener'];
        }

        return $container->privates['Ibexa\\Personalization\\Event\\Listener\\ConfigurePersonalizationMenuListener'] = new \Ibexa\Personalization\Event\Listener\ConfigurePersonalizationMenuListener($a, ($container->privates['Ibexa\\Personalization\\Security\\Service\\SecurityService'] ?? $container->load('getSecurityServiceService')), ($container->privates['Ibexa\\Personalization\\Permission\\PermissionChecker'] ?? $container->load('getPermissionChecker2Service')), $b);
    }
}
