<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentTypeGroupMigrationGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Migration\Generator\ContentTypeGroup\ContentTypeGroupMigrationGenerator' shared autowired service.
     *
     * @return \Ibexa\Migration\Generator\ContentTypeGroup\ContentTypeGroupMigrationGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Generator/MigrationGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Generator/ContentTypeGroup/ContentTypeGroupMigrationGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Generator/StepBuilder/StepFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Log/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Generator/StepBuilder/AbstractStepFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Generator/ContentTypeGroup/StepBuilder/Factory.php';

        $a = new \Ibexa\Migration\Generator\ContentTypeGroup\StepBuilder\Factory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'create' => ['privates', 'Ibexa\\Migration\\Generator\\ContentTypeGroup\\StepBuilder\\Create', 'getCreate2Service', true],
            'delete' => ['privates', 'Ibexa\\Migration\\Generator\\ContentTypeGroup\\StepBuilder\\Delete', 'getDeleteService', true],
            'update' => ['privates', 'Ibexa\\Migration\\Generator\\ContentTypeGroup\\StepBuilder\\Update', 'getUpdateService', true],
        ], [
            'create' => 'Ibexa\\Migration\\Generator\\ContentTypeGroup\\StepBuilder\\Create',
            'delete' => 'Ibexa\\Migration\\Generator\\ContentTypeGroup\\StepBuilder\\Delete',
            'update' => 'Ibexa\\Migration\\Generator\\ContentTypeGroup\\StepBuilder\\Update',
        ]), 'content_type_group');
        $a->setLogger(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        return $container->privates['Ibexa\\Migration\\Generator\\ContentTypeGroup\\ContentTypeGroupMigrationGenerator'] = new \Ibexa\Migration\Generator\ContentTypeGroup\ContentTypeGroupMigrationGenerator(($container->services['ibexa.api.service.content_type'] ?? $container->getIbexa_Api_Service_ContentTypeService()), $a);
    }
}
