<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountryComparisonEngineService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\VersionComparison\Engine\FieldType\CountryComparisonEngine' shared autowired service.
     *
     * @return \Ibexa\VersionComparison\Engine\FieldType\CountryComparisonEngine
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/version-comparison/src/contracts/Engine/FieldTypeComparisonEngine.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/version-comparison/src/lib/Engine/FieldType/CountryComparisonEngine.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/version-comparison/src/lib/Engine/Value/HashMapComparisonEngine.php';

        return $container->privates['Ibexa\\VersionComparison\\Engine\\FieldType\\CountryComparisonEngine'] = new \Ibexa\VersionComparison\Engine\FieldType\CountryComparisonEngine(new \Ibexa\VersionComparison\Engine\Value\HashMapComparisonEngine());
    }
}
