<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentTypeInfoListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Rest\Server\Output\ValueObjectVisitor\ContentTypeInfoList' shared service.
     *
     * @return \Ibexa\Rest\Server\Output\ValueObjectVisitor\ContentTypeInfoList
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/rest/src/contracts/Output/ValueObjectVisitor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/rest/src/lib/Server/Output/ValueObjectVisitor/ContentTypeInfoList.php';

        $container->privates['Ibexa\\Rest\\Server\\Output\\ValueObjectVisitor\\ContentTypeInfoList'] = $instance = new \Ibexa\Rest\Server\Output\ValueObjectVisitor\ContentTypeInfoList();

        $instance->setRequestParser(($container->privates['Ibexa\\Bundle\\Rest\\RequestParser\\Router'] ?? $container->getRouter2Service()));
        $instance->setRouter(($container->services['router'] ?? $container->getRouterService()));
        $instance->setTemplateRouter(($container->privates['Ibexa\\Bundle\\Core\\Routing\\DefaultRouter'] ?? $container->load('getDefaultRouterService')));

        return $instance;
    }
}
