<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentViewTabSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Taxonomy\Event\Subscriber\ContentViewTabSubscriber' shared autowired service.
     *
     * @return \Ibexa\Taxonomy\Event\Subscriber\ContentViewTabSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/taxonomy/src/lib/Event/Subscriber/ContentViewTabSubscriber.php';

        return $container->privates['Ibexa\\Taxonomy\\Event\\Subscriber\\ContentViewTabSubscriber'] = new \Ibexa\Taxonomy\Event\Subscriber\ContentViewTabSubscriber(($container->privates['Ibexa\\Taxonomy\\Service\\TaxonomyConfiguration'] ?? $container->getTaxonomyConfigurationService()));
    }
}
