<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContent3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Sj5nKyX.Ibexa\Contracts\Core\Repository\Values\Content\Content' shared service.
     *
     * @return \Ibexa\Contracts\Core\Repository\Values\Content\Content
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Sj5nKyX": it references class "Ibexa\\Contracts\\Core\\Repository\\Values\\Content\\Content" but no such service exists.');
    }
}
