<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompany3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QhIbcMF.Ibexa\Contracts\CorporateAccount\Values\Company' shared service.
     *
     * @return \Ibexa\Contracts\CorporateAccount\Values\Company
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QhIbcMF": it references class "Ibexa\\Contracts\\CorporateAccount\\Values\\Company" but no such service exists.');
    }
}
