<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentImageAssetMapperStrategyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\GraphQL\Mapper\ContentImageAssetMapperStrategy' shared autowired service.
     *
     * @return \Ibexa\GraphQL\Mapper\ContentImageAssetMapperStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/graphql/src/lib/Mapper/ImageAssetMapperStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/graphql/src/lib/Mapper/ContentImageAssetMapperStrategy.php';

        return $container->privates['Ibexa\\GraphQL\\Mapper\\ContentImageAssetMapperStrategy'] = new \Ibexa\GraphQL\Mapper\ContentImageAssetMapperStrategy(($container->privates['Ibexa\\Core\\FieldType\\ImageAsset\\AssetMapper'] ?? $container->getAssetMapperService()), ($container->privates['Ibexa\\GraphQL\\DataLoader\\CachedContentLoader'] ?? $container->load('getCachedContentLoaderService')));
    }
}
