<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentContextMenuBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Taxonomy\Menu\ContentContextMenuBuilder' shared autowired service.
     *
     * @return \Ibexa\Taxonomy\Menu\ContentContextMenuBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Menu/AbstractBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/taxonomy/src/lib/Menu/ContentContextMenuBuilder.php';

        $a = ($container->services['Ibexa\\AdminUi\\Menu\\MenuItemFactory'] ?? $container->load('getMenuItemFactoryService'));

        if (isset($container->services['Ibexa\\Taxonomy\\Menu\\ContentContextMenuBuilder'])) {
            return $container->services['Ibexa\\Taxonomy\\Menu\\ContentContextMenuBuilder'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['Ibexa\\Taxonomy\\Menu\\ContentContextMenuBuilder'])) {
            return $container->services['Ibexa\\Taxonomy\\Menu\\ContentContextMenuBuilder'];
        }
        $c = ($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService());

        if (isset($container->services['Ibexa\\Taxonomy\\Menu\\ContentContextMenuBuilder'])) {
            return $container->services['Ibexa\\Taxonomy\\Menu\\ContentContextMenuBuilder'];
        }
        $d = ($container->privates['Ibexa\\Taxonomy\\Tree\\TaxonomyTreeService'] ?? $container->load('getTaxonomyTreeServiceService'));

        if (isset($container->services['Ibexa\\Taxonomy\\Menu\\ContentContextMenuBuilder'])) {
            return $container->services['Ibexa\\Taxonomy\\Menu\\ContentContextMenuBuilder'];
        }

        return $container->services['Ibexa\\Taxonomy\\Menu\\ContentContextMenuBuilder'] = new \Ibexa\Taxonomy\Menu\ContentContextMenuBuilder($a, $b, $c, ($container->privates['Ibexa\\AdminUi\\Permission\\PermissionChecker'] ?? $container->load('getPermissionCheckerService')), ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()), $d);
    }
}
