<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentCreateExtension2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\SiteContext\Form\Extension\ContentCreateExtension' shared autowired service.
     *
     * @return \Ibexa\Bundle\SiteContext\Form\Extension\ContentCreateExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/site-context/src/bundle/Form/Extension/ContentCreateExtension.php';

        $a = ($container->privates['Ibexa\\SiteContext\\SiteContextService'] ?? $container->getSiteContextServiceService());

        if (isset($container->privates['Ibexa\\Bundle\\SiteContext\\Form\\Extension\\ContentCreateExtension'])) {
            return $container->privates['Ibexa\\Bundle\\SiteContext\\Form\\Extension\\ContentCreateExtension'];
        }

        return $container->privates['Ibexa\\Bundle\\SiteContext\\Form\\Extension\\ContentCreateExtension'] = new \Ibexa\Bundle\SiteContext\Form\Extension\ContentCreateExtension($a, ($container->services['ibexa.api.service.language'] ?? $container->getIbexa_Api_Service_LanguageService()), ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()));
    }
}
