<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigureMenuListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Scheduler\Menu\ConfigureMenuListener' shared autowired service.
     *
     * @return \Ibexa\Scheduler\Menu\ConfigureMenuListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/scheduler/src/lib/Menu/ConfigureMenuListener.php';

        $a = ($container->privates['Ibexa\\Scheduler\\Repository\\DateBasedPublisherService'] ?? $container->load('getDateBasedPublisherServiceService'));

        if (isset($container->privates['Ibexa\\Scheduler\\Menu\\ConfigureMenuListener'])) {
            return $container->privates['Ibexa\\Scheduler\\Menu\\ConfigureMenuListener'];
        }
        $b = ($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService());

        if (isset($container->privates['Ibexa\\Scheduler\\Menu\\ConfigureMenuListener'])) {
            return $container->privates['Ibexa\\Scheduler\\Menu\\ConfigureMenuListener'];
        }
        $c = ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService());

        if (isset($container->privates['Ibexa\\Scheduler\\Menu\\ConfigureMenuListener'])) {
            return $container->privates['Ibexa\\Scheduler\\Menu\\ConfigureMenuListener'];
        }

        return $container->privates['Ibexa\\Scheduler\\Menu\\ConfigureMenuListener'] = new \Ibexa\Scheduler\Menu\ConfigureMenuListener($a, $b, ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()), $c);
    }
}
