<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentCreateViewFilterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ContentForms\Content\View\Filter\ContentCreateViewFilter' shared autowired service.
     *
     * @return \Ibexa\ContentForms\Content\View\Filter\ContentCreateViewFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/lib/Content/View/Filter/ContentCreateViewFilter.php';

        $a = ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService());

        if (isset($container->privates['Ibexa\\ContentForms\\Content\\View\\Filter\\ContentCreateViewFilter'])) {
            return $container->privates['Ibexa\\ContentForms\\Content\\View\\Filter\\ContentCreateViewFilter'];
        }
        $b = ($container->services['ibexa.api.service.content_type'] ?? $container->getIbexa_Api_Service_ContentTypeService());

        if (isset($container->privates['Ibexa\\ContentForms\\Content\\View\\Filter\\ContentCreateViewFilter'])) {
            return $container->privates['Ibexa\\ContentForms\\Content\\View\\Filter\\ContentCreateViewFilter'];
        }
        $c = ($container->services['.container.private.form.factory'] ?? $container->get_Container_Private_Form_FactoryService());

        if (isset($container->privates['Ibexa\\ContentForms\\Content\\View\\Filter\\ContentCreateViewFilter'])) {
            return $container->privates['Ibexa\\ContentForms\\Content\\View\\Filter\\ContentCreateViewFilter'];
        }

        return $container->privates['Ibexa\\ContentForms\\Content\\View\\Filter\\ContentCreateViewFilter'] = new \Ibexa\ContentForms\Content\View\Filter\ContentCreateViewFilter($a, $b, $c, ($container->privates['Ibexa\\Core\\MVC\\Symfony\\Locale\\UserLanguagePreferenceProvider'] ?? $container->getUserLanguagePreferenceProviderService()));
    }
}
