<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDelete5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ProductCatalog\Migrations\Attribute\StepBuilder\Delete' shared autowired service.
     *
     * @return \Ibexa\ProductCatalog\Migrations\Attribute\StepBuilder\Delete
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Generator/StepBuilder/StepBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/Migrations/Attribute/StepBuilder/Delete.php';

        return $container->privates['Ibexa\\ProductCatalog\\Migrations\\Attribute\\StepBuilder\\Delete'] = new \Ibexa\ProductCatalog\Migrations\Attribute\StepBuilder\Delete();
    }
}
