<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardProvisioner2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\Dashboard\Installer\DashboardProvisioner' shared autowired service.
     *
     * @return \Ibexa\Bundle\Dashboard\Installer\DashboardProvisioner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/installer/src/lib/Provisioner/ProvisionerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/installer/src/lib/Provisioner/AbstractMigrationProvisioner.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/dashboard/src/bundle/Installer/DashboardProvisioner.php';

        return $container->privates['Ibexa\\Bundle\\Dashboard\\Installer\\DashboardProvisioner'] = new \Ibexa\Bundle\Dashboard\Installer\DashboardProvisioner(($container->privates['Ibexa\\Migration\\MigrationService'] ?? $container->load('getMigrationServiceService')), ($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
