<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDateFieldSubmissionConverterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FormBuilder\FormSubmission\Converter\DateFieldSubmissionConverter' shared autowired service.
     *
     * @return \Ibexa\FormBuilder\FormSubmission\Converter\DateFieldSubmissionConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/lib/FormSubmission/Converter/FieldSubmissionConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/lib/FormSubmission/Converter/GenericFieldSubmissionConverter.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/lib/FormSubmission/Converter/DateFieldSubmissionConverter.php';

        $a = ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService());

        if (isset($container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\DateFieldSubmissionConverter'])) {
            return $container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\DateFieldSubmissionConverter'];
        }
        $b = ($container->privates['Ibexa\\User\\UserSetting\\UserSettingService'] ?? $container->getUserSettingServiceService());

        if (isset($container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\DateFieldSubmissionConverter'])) {
            return $container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\DateFieldSubmissionConverter'];
        }

        return $container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\DateFieldSubmissionConverter'] = new \Ibexa\FormBuilder\FormSubmission\Converter\DateFieldSubmissionConverter('date', $a, $b, $a);
    }
}
