<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDecoratedFragmentRendererService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\PageBuilder\HTTP\Kernel\Fragment\DecoratedFragmentRenderer' shared autowired service.
     *
     * @return \Ibexa\PageBuilder\HTTP\Kernel\Fragment\DecoratedFragmentRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Fragment/FragmentRendererInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Fragment/RoutableFragmentRenderer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Fragment/AbstractSurrogateFragmentRenderer.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/page-builder/src/lib/HTTP/Kernel/Fragment/DecoratedFragmentRenderer.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/FragmentRenderer/BlockRenderOptionsFragmentRenderer.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/Fragment/SiteAccessSerializationTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/Fragment/DecoratedFragmentRenderer.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/page-builder/src/lib/HTTP/Kernel/ControllerResolver.php';

        $a = ($container->privates['fragment.renderer.inline'] ?? $container->load('getFragment_Renderer_InlineService'));

        if (isset($container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'])) {
            return $container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'];
        }
        $b = ($container->privates['fragment.renderer.esi.inner'] ?? $container->load('getFragment_Renderer_Esi_InnerService'));

        if (isset($container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'])) {
            return $container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'];
        }
        $c = ($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService());

        if (isset($container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'])) {
            return $container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'];
        }
        $d = ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService());

        if (isset($container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'])) {
            return $container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'];
        }
        $e = ($container->services['Ibexa\\FieldTypePage\\FieldType\\Page\\FieldDefinitionLocator'] ?? $container->getFieldDefinitionLocatorService());

        if (isset($container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'])) {
            return $container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'];
        }
        $f = ($container->services['ibexa.api.service.content_type'] ?? $container->getIbexa_Api_Service_ContentTypeService());

        if (isset($container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'])) {
            return $container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'];
        }
        $g = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'])) {
            return $container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'];
        }
        $h = ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService());

        if (isset($container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'])) {
            return $container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'];
        }
        $i = ($container->services['http_kernel'] ?? $container->getHttpKernelService());

        if (isset($container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'])) {
            return $container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'];
        }
        $j = new \Ibexa\Bundle\Core\Fragment\DecoratedFragmentRenderer($b);
        $j->setFragmentPath('/_fragment');
        $j->setSiteAccess(($container->privates['Ibexa\\Core\\MVC\\Symfony\\SiteAccess'] ?? ($container->privates['Ibexa\\Core\\MVC\\Symfony\\SiteAccess'] = new \Ibexa\Core\MVC\Symfony\SiteAccess('default', 'uninitialized'))));
        $k = ($container->privates['debug.controller_resolver'] ?? $container->getDebug_ControllerResolverService());

        return $container->privates['Ibexa\\PageBuilder\\HTTP\\Kernel\\Fragment\\DecoratedFragmentRenderer'] = new \Ibexa\PageBuilder\HTTP\Kernel\Fragment\DecoratedFragmentRenderer(($container->privates['esi'] ?? ($container->privates['esi'] = new \Symfony\Component\HttpKernel\HttpCache\Esi())), $a, ($container->privates['uri_signer'] ?? ($container->privates['uri_signer'] = new \Symfony\Component\HttpKernel\UriSigner($container->getEnv('APP_SECRET')))), new \Ibexa\FieldTypePage\FragmentRenderer\BlockRenderOptionsFragmentRenderer($j, $c, $d, $e, $f, $g, $k, $h, ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService())), new \Ibexa\PageBuilder\HTTP\Kernel\ControllerResolver($k), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['Ibexa\\PageBuilder\\Security\\EditorialMode\\TokenAuthenticator'] ?? $container->getTokenAuthenticatorService()), ($container->privates['Ibexa\\PageBuilder\\Security\\EditorialMode\\TokenManager'] ?? $container->getTokenManagerService()), ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()), $i);
    }
}
