<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteWorkflowSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Workflow\Event\Subscriber\DeleteWorkflowSubscriber' shared autowired service.
     *
     * @return \Ibexa\Workflow\Event\Subscriber\DeleteWorkflowSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/workflow/src/lib/Event/Subscriber/DeleteWorkflowSubscriber.php';

        return $container->privates['Ibexa\\Workflow\\Event\\Subscriber\\DeleteWorkflowSubscriber'] = new \Ibexa\Workflow\Event\Subscriber\DeleteWorkflowSubscriber(($container->privates['Ibexa\\Workflow\\Persistence\\Handler\\WorkflowHandler'] ?? $container->getWorkflowHandlerService()));
    }
}
