<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDAMImageAssetMapperStrategyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Connector\Dam\FieldType\ImageAsset\Mapper\DAMImageAssetMapperStrategy' shared autowired service.
     *
     * @return \Ibexa\Connector\Dam\FieldType\ImageAsset\Mapper\DAMImageAssetMapperStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/graphql/src/lib/Mapper/ImageAssetMapperStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/connector-dam/src/lib/FieldType/ImageAsset/Mapper/DAMImageAssetMapperStrategy.php';

        return $container->privates['Ibexa\\Connector\\Dam\\FieldType\\ImageAsset\\Mapper\\DAMImageAssetMapperStrategy'] = new \Ibexa\Connector\Dam\FieldType\ImageAsset\Mapper\DAMImageAssetMapperStrategy(($container->privates['Ibexa\\Connector\\Dam\\AssetService'] ?? $container->getAssetServiceService()));
    }
}
