<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExecutor5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Segmentation\StepExecutor\ActionExecutor\Segment\Executor' shared autowired service.
     *
     * @return \Ibexa\Segmentation\StepExecutor\ActionExecutor\Segment\Executor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ActionExecutor/ExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Log/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ActionExecutor/AbstractExecutor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/segmentation/src/lib/StepExecutor/ActionExecutor/Segment/Executor.php';

        return $container->privates['Ibexa\\Segmentation\\StepExecutor\\ActionExecutor\\Segment\\Executor'] = new \Ibexa\Segmentation\StepExecutor\ActionExecutor\Segment\Executor(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'assign_segment_to_user' => ['privates', 'Ibexa\\Segmentation\\StepExecutor\\ActionExecutor\\Segment\\AssignToUser', 'getAssignToUser2Service', true],
            'unassign_segment_from_user' => ['privates', 'Ibexa\\Segmentation\\StepExecutor\\ActionExecutor\\Segment\\UnassignFromUser', 'getUnassignFromUserService', true],
        ], [
            'assign_segment_to_user' => 'Ibexa\\Segmentation\\StepExecutor\\ActionExecutor\\Segment\\AssignToUser',
            'unassign_segment_from_user' => 'Ibexa\\Segmentation\\StepExecutor\\ActionExecutor\\Segment\\UnassignFromUser',
        ]));
    }
}
