<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEveryoneContentTabService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\AdminUi\Tab\Dashboard\EveryoneContentTab' shared autowired service.
     *
     * @return \Ibexa\AdminUi\Tab\Dashboard\EveryoneContentTab
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->privates['Ibexa\\AdminUi\\Tab\\Dashboard\\EveryoneContentTab'] = $container->createProxy('EveryoneContentTab_8cf0661', function () use ($container) {
                return \EveryoneContentTab_8cf0661::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/TabInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/AbstractTab.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/OrderedTabInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Tab/Dashboard/AbstractContentTab.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Tab/Dashboard/EveryoneContentTab.php';

        return new \Ibexa\AdminUi\Tab\Dashboard\EveryoneContentTab(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()), ($container->privates['Ibexa\\AdminUi\\Tab\\Dashboard\\PagerLocationToDataMapper'] ?? $container->load('getPagerLocationToDataMapperService')), ($container->services['ibexa.api.service.search'] ?? $container->getIbexa_Api_Service_SearchService()), ($container->privates['Ibexa\\AdminUi\\QueryType\\ContentLocationSubtreeQueryType'] ?? $container->getContentLocationSubtreeQueryTypeService()));
    }
}
