<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpressionLanguageProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\Migration\Serializer\Denormalizer\Template\ExpressionLanguageProvider' shared autowired service.
     *
     * @return \Ibexa\Bundle\Migration\Serializer\Denormalizer\Template\ExpressionLanguageProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/bundle/Serializer/Denormalizer/Template/ExpressionLanguageProvider.php';

        return $container->privates['Ibexa\\Bundle\\Migration\\Serializer\\Denormalizer\\Template\\ExpressionLanguageProvider'] = new \Ibexa\Bundle\Migration\Serializer\Denormalizer\Template\ExpressionLanguageProvider(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'env' => ['privates', 'ibexa.migrations.template.env', 'getIbexa_Migrations_Template_EnvService', true],
            'project_dir' => ['privates', 'Ibexa\\Bundle\\Migration\\Serializer\\Denormalizer\\Template\\ProjectDirectoryResolver', 'getProjectDirectoryResolverService', true],
            'reference' => ['privates', 'Ibexa\\Bundle\\Migration\\Serializer\\Denormalizer\\Template\\ReferenceResolver', 'getReferenceResolverService', true],
            'to_bool' => ['privates', 'ibexa.migrations.template.to_bool', 'getIbexa_Migrations_Template_ToBoolService', true],
            'to_float' => ['privates', 'ibexa.migrations.template.to_float', 'getIbexa_Migrations_Template_ToFloatService', true],
            'to_int' => ['privates', 'ibexa.migrations.template.to_int', 'getIbexa_Migrations_Template_ToIntService', true],
            'to_string' => ['privates', 'ibexa.migrations.template.to_string', 'getIbexa_Migrations_Template_ToStringService', true],
        ], [
            'env' => 'Closure',
            'project_dir' => 'Ibexa\\Bundle\\Migration\\Serializer\\Denormalizer\\Template\\ProjectDirectoryResolver',
            'reference' => 'Ibexa\\Bundle\\Migration\\Serializer\\Denormalizer\\Template\\ReferenceResolver',
            'to_bool' => 'Closure',
            'to_float' => 'Closure',
            'to_int' => 'Closure',
            'to_string' => 'Closure',
        ]));
    }
}
