<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailFieldMapperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FormBuilder\FieldType\Field\Mapper\EmailFieldMapper' shared autowired service.
     *
     * @return \Ibexa\FormBuilder\FieldType\Field\Mapper\EmailFieldMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/contracts/FieldType/Field/FieldMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/lib/FieldType/Field/Mapper/GenericFieldMapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/lib/FieldType/Field/Mapper/EmailFieldMapper.php';

        return $container->services['Ibexa\\FormBuilder\\FieldType\\Field\\Mapper\\EmailFieldMapper'] = new \Ibexa\FormBuilder\FieldType\Field\Mapper\EmailFieldMapper('email', 'Ibexa\\FormBuilder\\Form\\Type\\Field\\EmailFieldType');
    }
}
