<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditorContentListTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Personalization\Form\Type\Model\EditorContentListType' shared autowired service.
     *
     * @return \Ibexa\Personalization\Form\Type\Model\EditorContentListType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/personalization/src/lib/Form/Type/Model/EditorContentListType.php';

        $a = ($container->privates['Ibexa\\Personalization\\Service\\Search\\SearchService'] ?? $container->load('getSearchServiceService'));

        if (isset($container->privates['Ibexa\\Personalization\\Form\\Type\\Model\\EditorContentListType'])) {
            return $container->privates['Ibexa\\Personalization\\Form\\Type\\Model\\EditorContentListType'];
        }
        $b = ($container->privates['Ibexa\\Personalization\\Service\\Setting\\DefaultSiteAccessSettingService'] ?? $container->load('getDefaultSiteAccessSettingServiceService'));

        if (isset($container->privates['Ibexa\\Personalization\\Form\\Type\\Model\\EditorContentListType'])) {
            return $container->privates['Ibexa\\Personalization\\Form\\Type\\Model\\EditorContentListType'];
        }

        return $container->privates['Ibexa\\Personalization\\Form\\Type\\Model\\EditorContentListType'] = new \Ibexa\Personalization\Form\Type\Model\EditorContentListType($a, $b);
    }
}
