<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormMapperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FormBuilder\Form\Mapper\FormMapper' shared autowired service.
     *
     * @return \Ibexa\FormBuilder\Form\Mapper\FormMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/contracts/FieldType/FieldValueFormMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/lib/Form/Mapper/FormMapper.php';

        $a = ($container->services['Ibexa\\FormBuilder\\FieldType\\Type'] ?? $container->getType6Service());

        if (isset($container->services['Ibexa\\FormBuilder\\Form\\Mapper\\FormMapper'])) {
            return $container->services['Ibexa\\FormBuilder\\Form\\Mapper\\FormMapper'];
        }

        return $container->services['Ibexa\\FormBuilder\\Form\\Mapper\\FormMapper'] = new \Ibexa\FormBuilder\Form\Mapper\FormMapper($a);
    }
}
