<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFutureHideEventTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Scheduler\Calendar\FutureHideEventType' shared autowired service.
     *
     * @return \Ibexa\Scheduler\Calendar\FutureHideEventType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/calendar/src/contracts/EventType/EventTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/scheduler/src/lib/Calendar/FutureHideEventType.php';

        return $container->privates['Ibexa\\Scheduler\\Calendar\\FutureHideEventType'] = new \Ibexa\Scheduler\Calendar\FutureHideEventType(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Ibexa\\Scheduler\\Calendar\\EventAction\\RescheduleHideEventAction'] ?? $container->load('getRescheduleHideEventActionService'));
            yield 1 => ($container->privates['Ibexa\\Scheduler\\Calendar\\EventAction\\UnscheduleHideEventAction'] ?? $container->load('getUnscheduleHideEventActionService'));
        }, 2), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()));
    }
}
