<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFastlyMigrateConfigurationCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\Fastly\Command\FastlyMigrateConfigurationCommand' shared autowired service.
     *
     * @return \Ibexa\Bundle\Fastly\Command\FastlyMigrateConfigurationCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fastly/src/bundle/Command/FastlyMigrateConfigurationCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fastly/src/lib/ImageOptimizer/AliasConfigurationMapper.php';

        $a = ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService());

        $container->privates['Ibexa\\Bundle\\Fastly\\Command\\FastlyMigrateConfigurationCommand'] = $instance = new \Ibexa\Bundle\Fastly\Command\FastlyMigrateConfigurationCommand($container->parameters['ibexa.site_access.list'], $a, new \Ibexa\Fastly\ImageOptimizer\AliasConfigurationMapper($a));

        $instance->addOption('siteaccess', NULL, 4, 'SiteAccess to use for operations. If not provided, default siteaccess will be used');
        $instance->setName('ibexa:fastly:migrate-configuration');
        $instance->setDescription('Dumps draft Fastly IO YAML configuration migrated from built-in alias variations.');

        return $instance;
    }
}
