<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldSubmissionConverterRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FormBuilder\FormSubmission\Converter\FieldSubmissionConverterRegistry' shared autowired service.
     *
     * @return \Ibexa\FormBuilder\FormSubmission\Converter\FieldSubmissionConverterRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/lib/FormSubmission/Converter/FieldSubmissionConverterRegistry.php';

        $a = ($container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\GenericFieldSubmissionConverter'] ?? $container->load('getGenericFieldSubmissionConverterService'));

        if (isset($container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\FieldSubmissionConverterRegistry'])) {
            return $container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\FieldSubmissionConverterRegistry'];
        }

        return $container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\FieldSubmissionConverterRegistry'] = new \Ibexa\FormBuilder\FormSubmission\Converter\FieldSubmissionConverterRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\BooleanFieldSubmissionConverter'] ?? $container->load('getBooleanFieldSubmissionConverterService'));
            yield 1 => ($container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\ArrayFieldSubmissionConverter'] ?? $container->load('getArrayFieldSubmissionConverterService'));
            yield 2 => ($container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\DateFieldSubmissionConverter'] ?? $container->load('getDateFieldSubmissionConverterService'));
            yield 3 => ($container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\FileFieldSubmissionConverter'] ?? $container->load('getFileFieldSubmissionConverterService'));
            yield 4 => ($container->services['Ibexa\\FormBuilder\\FormSubmission\\Converter\\MultilineFieldSubmissionConverter'] ?? $container->load('getMultilineFieldSubmissionConverterService'));
        }, 5), $a);
    }
}
