<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldTypeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Migration\Service\FieldTypeService' shared autowired service.
     *
     * @return \Ibexa\Migration\Service\FieldTypeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Service/FieldTypeServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Service/FieldTypeService.php';

        return $container->privates['Ibexa\\Migration\\Service\\FieldTypeService'] = new \Ibexa\Migration\Service\FieldTypeService(($container->privates['Ibexa\\Core\\FieldType\\FieldTypeRegistry'] ?? $container->getFieldTypeRegistryService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
