<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupedContentFormFieldsProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ContentForms\Content\Form\Provider\GroupedContentFormFieldsProvider' shared service.
     *
     * @return \Ibexa\ContentForms\Content\Form\Provider\GroupedContentFormFieldsProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/contracts/Content/Form/Provider/GroupedContentFormFieldsProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/lib/Content/Form/Provider/GroupedContentFormFieldsProvider.php';

        return $container->privates['Ibexa\\ContentForms\\Content\\Form\\Provider\\GroupedContentFormFieldsProvider'] = new \Ibexa\ContentForms\Content\Form\Provider\GroupedContentFormFieldsProvider(($container->privates['Ibexa\\CorporateAccount\\FieldType\\FieldGroupsListDecorator'] ?? $container->getFieldGroupsListDecoratorService()));
    }
}
