<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHelpExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FormBuilder\Form\Type\Extension\HelpExtension' shared autowired service.
     *
     * @return \Ibexa\FormBuilder\Form\Type\Extension\HelpExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/lib/Form/Type/Extension/HelpExtension.php';

        return $container->services['Ibexa\\FormBuilder\\Form\\Type\\Extension\\HelpExtension'] = new \Ibexa\FormBuilder\Form\Type\Extension\HelpExtension();
    }
}
