<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpCacheServiceInfoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\SystemInfo\Service\HttpCacheServiceInfo' shared service.
     *
     * @return \Ibexa\SystemInfo\Service\HttpCacheServiceInfo
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/Service/ServiceInfo.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/Service/HttpCacheServiceInfo.php';

        return $container->privates['Ibexa\\SystemInfo\\Service\\HttpCacheServiceInfo'] = new \Ibexa\SystemInfo\Service\HttpCacheServiceInfo($container->getEnv('HTTPCACHE_PURGE_TYPE'));
    }
}
