<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHasChildrenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasChildren' shared autowired service.
     *
     * @return \Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasChildren
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Form/TrashLocationOptionProvider/TrashLocationOptionProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Form/TrashLocationOptionProvider/HasChildren.php';

        $a = ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService());

        if (isset($container->privates['Ibexa\\AdminUi\\Form\\TrashLocationOptionProvider\\HasChildren'])) {
            return $container->privates['Ibexa\\AdminUi\\Form\\TrashLocationOptionProvider\\HasChildren'];
        }

        return $container->privates['Ibexa\\AdminUi\\Form\\TrashLocationOptionProvider\\HasChildren'] = new \Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasChildren($a, ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()));
    }
}
