<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIsFieldEmptyVisitorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Elasticsearch\Query\CriterionVisitor\IsFieldEmptyVisitor' shared autowired service.
     *
     * @return \Ibexa\Elasticsearch\Query\CriterionVisitor\IsFieldEmptyVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/elasticsearch/src/contracts/Query/CriterionVisitor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/elasticsearch/src/lib/Query/CriterionVisitor/IsFieldEmptyVisitor.php';

        return $container->privates['Ibexa\\Elasticsearch\\Query\\CriterionVisitor\\IsFieldEmptyVisitor'] = new \Ibexa\Elasticsearch\Query\CriterionVisitor\IsFieldEmptyVisitor(($container->privates['Ibexa\\Core\\Search\\Common\\FieldNameResolver'] ?? $container->getFieldNameResolverService()), ($container->privates['Ibexa\\Core\\Search\\Common\\FieldNameGenerator'] ?? $container->getFieldNameGeneratorService()));
    }
}
