<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIbexa_Core_Io_Migration_FileLister_MediaFileListerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ibexa.core.io.migration.file_lister.media_file_lister' shared service.
     *
     * @return \Ibexa\Bundle\IO\Migration\FileLister\BinaryFileLister
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->privates['ibexa.core.io.migration.file_lister.media_file_lister'] = $container->createProxy('BinaryFileLister_570e673', function () use ($container) {
                return \BinaryFileLister_570e673::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/IO/Migration/MigrationHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/IO/Migration/MigrationHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/IO/Migration/FileListerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/IO/Migration/FileLister/BinaryFileLister.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/IO/Migration/FileLister/FileIteratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/IO/Migration/FileLister/FileIterator/LegacyStorageFileIterator.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/IO/Migration/FileLister/FileRowReaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/IO/Migration/FileLister/FileRowReader/LegacyStorageFileRowReader.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/IO/Migration/FileLister/FileRowReader/LegacyStorageMediaFileRowReader.php';

        return new \Ibexa\Bundle\IO\Migration\FileLister\BinaryFileLister(($container->privates['ibexa.core.io.metadata_handler.registry'] ?? $container->getIbexa_Core_Io_MetadataHandler_RegistryService()), ($container->privates['ibexa.core.io.binarydata_handler.registry'] ?? $container->getIbexa_Core_Io_BinarydataHandler_RegistryService()), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), new \Ibexa\Bundle\IO\Migration\FileLister\FileIterator\LegacyStorageFileIterator(new \Ibexa\Bundle\IO\Migration\FileLister\FileRowReader\LegacyStorageMediaFileRowReader(($container->services['ibexa.persistence.connection'] ?? $container->getIbexa_Persistence_ConnectionService()))), 'original');
    }
}
