<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Core\Search\Legacy\Content\Indexer' shared service.
     *
     * @return \Ibexa\Core\Search\Legacy\Content\Indexer
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->privates['Ibexa\\Core\\Search\\Legacy\\Content\\Indexer'] = $container->createProxy('Indexer_317bf68', function () use ($container) {
                return \Indexer_317bf68::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/Search/Common/Indexer.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/Search/Common/IncrementalIndexer.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/Search/Legacy/Content/Indexer.php';

        return new \Ibexa\Core\Search\Legacy\Content\Indexer(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->privates['Ibexa\\Contracts\\Core\\Persistence\\Handler'] ?? $container->getHandler11Service()), ($container->services['ibexa.persistence.connection'] ?? $container->getIbexa_Persistence_ConnectionService()), ($container->privates['Ibexa\\Core\\Search\\Legacy\\Content\\Handler'] ?? $container->getHandler12Service()));
    }
}
