<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIbexa_ContentView_MatcherFactory_DynamicallyConfigured_InnerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ibexa.content_view.matcher_factory.dynamically_configured.inner' shared service.
     *
     * @return \Ibexa\Bundle\Core\Matcher\ServiceAwareMatcherFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/Matcher/MatcherFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/Matcher/ConfigurableMatcherFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/Matcher/ClassNameMatcherFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/Matcher/ServiceAwareMatcherFactory.php';

        $a = ($container->privates['Ibexa\\Bundle\\Core\\Matcher\\ViewMatcherRegistry'] ?? $container->load('getViewMatcherRegistryService'));

        if (isset($container->privates['ibexa.content_view.matcher_factory.dynamically_configured.inner'])) {
            return $container->privates['ibexa.content_view.matcher_factory.dynamically_configured.inner'];
        }
        $b = ($container->services['ibexa.api.repository'] ?? $container->getIbexa_Api_RepositoryService());

        if (isset($container->privates['ibexa.content_view.matcher_factory.dynamically_configured.inner'])) {
            return $container->privates['ibexa.content_view.matcher_factory.dynamically_configured.inner'];
        }

        return $container->privates['ibexa.content_view.matcher_factory.dynamically_configured.inner'] = new \Ibexa\Bundle\Core\Matcher\ServiceAwareMatcherFactory($a, $b, 'Ibexa\\Core\\MVC\\Symfony\\Matcher\\ContentBased');
    }
}
