<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIbexa_Solr_Query_Common_AggregationResultExtractor_ObjectStateTermService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ibexa.solr.query.common.aggregation_result_extractor.object_state_term' shared autowired service.
     *
     * @return \Ibexa\Solr\ResultExtractor\AggregationResultExtractor\TermAggregationResultExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/solr/src/contracts/ResultExtractor/AggregationResultExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/solr/src/lib/ResultExtractor/AggregationResultExtractor/TermAggregationResultExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/solr/src/contracts/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/solr/src/lib/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper/ObjectStateAggregationKeyMapper.php';

        return $container->privates['ibexa.solr.query.common.aggregation_result_extractor.object_state_term'] = new \Ibexa\Solr\ResultExtractor\AggregationResultExtractor\TermAggregationResultExtractor('Ibexa\\Contracts\\Core\\Repository\\Values\\Content\\Query\\Aggregation\\ObjectStateTermAggregation', new \Ibexa\Solr\ResultExtractor\AggregationResultExtractor\TermAggregationKeyMapper\ObjectStateAggregationKeyMapper(($container->services['ibexa.api.service.object_state'] ?? $container->getIbexa_Api_Service_ObjectStateService())));
    }
}
