<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvitationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\AdminUi\Controller\User\InvitationController' shared autowired service.
     *
     * @return \Ibexa\Bundle\AdminUi\Controller\User\InvitationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/bundle/Controller/User/InvitationController.php';

        return $container->services['Ibexa\\Bundle\\AdminUi\\Controller\\User\\InvitationController'] = new \Ibexa\Bundle\AdminUi\Controller\User\InvitationController(($container->services['.container.private.form.factory'] ?? $container->get_Container_Private_Form_FactoryService()), ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService()), ($container->privates['Ibexa\\User\\Invitation\\InvitationService'] ?? $container->getInvitationServiceService()), ($container->privates['Ibexa\\User\\Invitation\\MailSender'] ?? $container->load('getMailSenderService')), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->privates['Ibexa\\AdminUi\\Notification\\TranslatableNotificationHandler'] ?? $container->getTranslatableNotificationHandlerService()), ($container->privates['Ibexa\\Core\\MVC\\Symfony\\SiteAccess\\SiteAccessService'] ?? $container->getSiteAccessServiceService()), ($container->services['router'] ?? $container->getRouterService()));
    }
}
