<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvitationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\User\Form\Type\Invitation\InvitationType' shared autowired service.
     *
     * @return \Ibexa\User\Form\Type\Invitation\InvitationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/user/src/lib/Form/Type/Invitation/InvitationType.php';

        $a = ($container->privates['Ibexa\\User\\Invitation\\InvitationService'] ?? $container->getInvitationServiceService());

        if (isset($container->privates['Ibexa\\User\\Form\\Type\\Invitation\\InvitationType'])) {
            return $container->privates['Ibexa\\User\\Form\\Type\\Invitation\\InvitationType'];
        }

        return $container->privates['Ibexa\\User\\Form\\Type\\Invitation\\InvitationType'] = new \Ibexa\User\Form\Type\Invitation\InvitationType($a);
    }
}
