<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIbexa_Migrations_Kaliop_Io_Flysystem_DefaultFilesystemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ibexa.migrations.kaliop.io.flysystem.default_filesystem' shared autowired service.
     *
     * @return \League\Flysystem\Filesystem
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->privates['ibexa.migrations.kaliop.io.flysystem.default_filesystem'] = $container->createProxy('Filesystem_7103de5', function () use ($container) {
                return \Filesystem_7103de5::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        return new \League\Flysystem\Filesystem(($container->privates['ibexa.migrations.kaliop.io.flysystem.default_adapter'] ?? $container->load('getIbexa_Migrations_Kaliop_Io_Flysystem_DefaultAdapterService')));
    }
}
