<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIbexa_Migrations_ReferenceDefinition_Resolver_SectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ibexa.migrations.reference_definition.resolver.section' shared autowired service.
     *
     * @return \Ibexa\Migration\StepExecutor\ReferenceDefinition\Resolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ReferenceDefinition/ResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ReferenceDefinition/Resolver.php';

        return $container->privates['ibexa.migrations.reference_definition.resolver.section'] = new \Ibexa\Migration\StepExecutor\ReferenceDefinition\Resolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'section_id' => ['privates', 'Ibexa\\Migration\\StepExecutor\\ReferenceDefinition\\Section\\SectionIdResolver', 'getSectionIdResolverService', true],
        ], [
            'section_id' => 'Ibexa\\Migration\\StepExecutor\\ReferenceDefinition\\Section\\SectionIdResolver',
        ]));
    }
}
