<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Taxonomy\View\Matcher\TaxonomyEntryBased\Id' shared autowired service.
     *
     * @return \Ibexa\Taxonomy\View\Matcher\TaxonomyEntryBased\Id
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/Matcher/ViewMatcherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/Matcher/ContentBased/MatcherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/taxonomy/src/lib/View/Matcher/TaxonomyEntryBased/AbstractMatcher.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/taxonomy/src/lib/View/Matcher/TaxonomyEntryBased/Id.php';

        $a = ($container->privates['Ibexa\\Taxonomy\\Service\\Event\\TaxonomyService'] ?? $container->getTaxonomyServiceService());

        if (isset($container->privates['Ibexa\\Taxonomy\\View\\Matcher\\TaxonomyEntryBased\\Id'])) {
            return $container->privates['Ibexa\\Taxonomy\\View\\Matcher\\TaxonomyEntryBased\\Id'];
        }

        return $container->privates['Ibexa\\Taxonomy\\View\\Matcher\\TaxonomyEntryBased\\Id'] = new \Ibexa\Taxonomy\View\Matcher\TaxonomyEntryBased\Id($a);
    }
}
