<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIbexa_Migrations_ReferenceDefinition_Resolver_ContentTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ibexa.migrations.reference_definition.resolver.content_type' shared autowired service.
     *
     * @return \Ibexa\Migration\StepExecutor\ReferenceDefinition\Resolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ReferenceDefinition/ResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ReferenceDefinition/Resolver.php';

        return $container->privates['ibexa.migrations.reference_definition.resolver.content_type'] = new \Ibexa\Migration\StepExecutor\ReferenceDefinition\Resolver(($container->privates['.service_locator.Xbsa8iG'] ?? ($container->privates['.service_locator.Xbsa8iG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [], []))));
    }
}
