<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIbexa_ProductCatalog_Ui_Menu_CatalogViewContextMenuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'ibexa.product_catalog.ui.menu.catalog_view_context_menu' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Menu\CatalogViewContextMenuBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Menu/AbstractBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Menu/CatalogViewContextMenuBuilder.php';

        $a = ($container->services['Ibexa\\AdminUi\\Menu\\MenuItemFactory'] ?? $container->load('getMenuItemFactoryService'));

        if (isset($container->services['ibexa.product_catalog.ui.menu.catalog_view_context_menu'])) {
            return $container->services['ibexa.product_catalog.ui.menu.catalog_view_context_menu'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['ibexa.product_catalog.ui.menu.catalog_view_context_menu'])) {
            return $container->services['ibexa.product_catalog.ui.menu.catalog_view_context_menu'];
        }
        $c = ($container->services['.container.private.state_machine.ibexa_catalog'] ?? $container->get_Container_Private_StateMachine_IbexaCatalogService());

        if (isset($container->services['ibexa.product_catalog.ui.menu.catalog_view_context_menu'])) {
            return $container->services['ibexa.product_catalog.ui.menu.catalog_view_context_menu'];
        }

        return $container->services['ibexa.product_catalog.ui.menu.catalog_view_context_menu'] = new \Ibexa\Bundle\ProductCatalog\Menu\CatalogViewContextMenuBuilder($a, $b, ($container->privates['Ibexa\\ProductCatalog\\Local\\Permission\\PermissionResolver'] ?? $container->getPermissionResolverService()), $c, ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()));
    }
}
