<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIbexa_Elasticsearch_Query_Common_AggregationVisitor_ContentTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ibexa.elasticsearch.query.common.aggregation_visitor.content_type' shared autowired service.
     *
     * @return \Ibexa\Elasticsearch\Query\AggregationVisitor\TermAggregationVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/elasticsearch/src/contracts/Query/AggregationVisitor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/elasticsearch/src/lib/Query/AggregationVisitor/AbstractTermAggregationVisitor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/elasticsearch/src/lib/Query/AggregationVisitor/TermAggregationVisitor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/elasticsearch/src/lib/Query/AggregationVisitor/Factory/SearchFieldAggregationVisitorFactory.php';

        return $container->privates['ibexa.elasticsearch.query.common.aggregation_visitor.content_type'] = ($container->privates['Ibexa\\Elasticsearch\\Query\\AggregationVisitor\\Factory\\SearchFieldAggregationVisitorFactory'] ?? ($container->privates['Ibexa\\Elasticsearch\\Query\\AggregationVisitor\\Factory\\SearchFieldAggregationVisitorFactory'] = new \Ibexa\Elasticsearch\Query\AggregationVisitor\Factory\SearchFieldAggregationVisitorFactory()))->createTermAggregationVisitor('Ibexa\\Contracts\\Core\\Repository\\Values\\Content\\Query\\Aggregation\\ContentTypeTermAggregation', 'content_type_id_id');
    }
}
