<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntlMoneyFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ProductCatalog\Money\IntlMoneyFactory' shared autowired service.
     *
     * @return \Ibexa\ProductCatalog\Money\IntlMoneyFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/Money/IntlMoneyFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/NumberFormatter/NumberFormatterFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/NumberFormatter/NumberFormatterFactory.php';

        $a = ($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\Event\\CurrencyService'] ?? $container->getCurrencyServiceService());

        if (isset($container->privates['Ibexa\\ProductCatalog\\Money\\IntlMoneyFactory'])) {
            return $container->privates['Ibexa\\ProductCatalog\\Money\\IntlMoneyFactory'];
        }

        return $container->privates['Ibexa\\ProductCatalog\\Money\\IntlMoneyFactory'] = new \Ibexa\ProductCatalog\Money\IntlMoneyFactory($a, new \Ibexa\ProductCatalog\NumberFormatter\NumberFormatterFactory(($container->privates['Ibexa\\ProductCatalog\\NumberFormatter\\LocaleProvider\\LocaleResolver'] ?? $container->load('getLocaleResolverService')), 2, '', [6 => 16]));
    }
}
