<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIbexa_Api_SearchEngine_Legacy_ConnectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ibexa.api.search_engine.legacy.connection' shared service.
     *
     * @return \Doctrine\DBAL\Connection
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->privates['ibexa.api.search_engine.legacy.connection'] = $container->createProxy('Connection_82e3d72', function () use ($container) {
                return \Connection_82e3d72::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/LegacySearchEngine/ApiLoader/ConnectionFactory.php';

        $a = new \Ibexa\Bundle\LegacySearchEngine\ApiLoader\ConnectionFactory(($container->services['Ibexa\\Bundle\\Core\\ApiLoader\\RepositoryConfigurationProvider'] ?? $container->getRepositoryConfigurationProviderService()));
        $a->setContainer($container);

        return $a->getConnection();
    }
}
