<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIbexa_ProductCatalog_Search_Solr_AggregationResultExtractor_ProductStockRangeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ibexa.product_catalog.search.solr.aggregation_result_extractor.product_stock_range' shared autowired service.
     *
     * @return \Ibexa\Solr\ResultExtractor\AggregationResultExtractor\RangeAggregationResultExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/solr/src/contracts/ResultExtractor/AggregationResultExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/solr/src/lib/ResultExtractor/AggregationResultExtractor/RangeAggregationResultExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/solr/src/contracts/ResultExtractor/AggregationResultExtractor/RangeAggregationKeyMapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/solr/src/lib/ResultExtractor/AggregationResultExtractor/RangeAggregationKeyMapper/IntRangeAggregationKeyMapper.php';

        return $container->privates['ibexa.product_catalog.search.solr.aggregation_result_extractor.product_stock_range'] = new \Ibexa\Solr\ResultExtractor\AggregationResultExtractor\RangeAggregationResultExtractor('Ibexa\\Contracts\\ProductCatalog\\Values\\Product\\Query\\Aggregation\\ProductStockRangeAggregation', ($container->privates['Ibexa\\Solr\\ResultExtractor\\AggregationResultExtractor\\RangeAggregationKeyMapper\\IntRangeAggregationKeyMapper'] ?? ($container->privates['Ibexa\\Solr\\ResultExtractor\\AggregationResultExtractor\\RangeAggregationKeyMapper\\IntRangeAggregationKeyMapper'] = new \Ibexa\Solr\ResultExtractor\AggregationResultExtractor\RangeAggregationKeyMapper\IntRangeAggregationKeyMapper())));
    }
}
