<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonUpdateSerializerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Solr\Gateway\UpdateSerializer\JsonUpdateSerializer' shared autowired service.
     *
     * @return \Ibexa\Solr\Gateway\UpdateSerializer\JsonUpdateSerializer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/solr/src/lib/Gateway/UpdateSerializer/UpdateSerializer.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/solr/src/lib/Gateway/UpdateSerializer/JsonUpdateSerializer.php';

        return new \Ibexa\Solr\Gateway\UpdateSerializer\JsonUpdateSerializer(($container->privates['Ibexa\\Core\\Search\\Common\\FieldValueMapper\\Aggregate'] ?? $container->getAggregateService()), ($container->privates['Ibexa\\Core\\Search\\Common\\FieldNameGenerator'] ?? $container->getFieldNameGeneratorService()));
    }
}
