<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageChoiceLoaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\AdminUi\Form\Type\ChoiceList\Loader\LanguageChoiceLoader' shared autowired service.
     *
     * @return \Ibexa\AdminUi\Form\Type\ChoiceList\Loader\LanguageChoiceLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Form/Type/ChoiceList/Loader/ConfiguredLanguagesChoiceLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Form/Type/ChoiceList/Loader/LanguageChoiceLoader.php';

        return $container->privates['Ibexa\\AdminUi\\Form\\Type\\ChoiceList\\Loader\\LanguageChoiceLoader'] = new \Ibexa\AdminUi\Form\Type\ChoiceList\Loader\LanguageChoiceLoader(($container->services['ibexa.api.service.language'] ?? $container->getIbexa_Api_Service_LanguageService()), ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()));
    }
}
