<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageChoiceType3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\Search\Form\Type\LanguageChoiceType' shared service.
     *
     * @return \Ibexa\Bundle\Search\Form\Type\LanguageChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/search/src/bundle/Form/Type/LanguageChoiceType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/search/src/bundle/Form/ChoiceLoader/ConfiguredLanguagesChoiceLoader.php';

        return $container->privates['Ibexa\\Bundle\\Search\\Form\\Type\\LanguageChoiceType'] = new \Ibexa\Bundle\Search\Form\Type\LanguageChoiceType(new \Ibexa\Bundle\Search\Form\ChoiceLoader\ConfiguredLanguagesChoiceLoader(($container->services['ibexa.api.service.language'] ?? $container->getIbexa_Api_Service_LanguageService()), ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService())));
    }
}
