<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationChildrenTermAggregationVisitorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Elasticsearch\Query\AggregationVisitor\LocationChildrenTermAggregationVisitor' shared autowired service.
     *
     * @return \Ibexa\Elasticsearch\Query\AggregationVisitor\LocationChildrenTermAggregationVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/elasticsearch/src/lib/Query/AggregationVisitor/Factory/SearchFieldAggregationVisitorFactory.php';

        return $container->privates['Ibexa\\Elasticsearch\\Query\\AggregationVisitor\\LocationChildrenTermAggregationVisitor'] = ($container->privates['Ibexa\\Elasticsearch\\Query\\AggregationVisitor\\Factory\\SearchFieldAggregationVisitorFactory'] ?? ($container->privates['Ibexa\\Elasticsearch\\Query\\AggregationVisitor\\Factory\\SearchFieldAggregationVisitorFactory'] = new \Ibexa\Elasticsearch\Query\AggregationVisitor\Factory\SearchFieldAggregationVisitorFactory()))->createTermAggregationVisitor('Ibexa\\Contracts\\Core\\Repository\\Values\\Content\\Query\\Aggregation\\Location\\LocationChildrenTermAggregation', 'parent_id_id');
    }
}
