<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocaleResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ProductCatalog\NumberFormatter\LocaleProvider\LocaleResolver' shared autowired service.
     *
     * @return \Ibexa\ProductCatalog\NumberFormatter\LocaleProvider\LocaleResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/NumberFormatter/LocaleProvider/LocaleResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/NumberFormatter/LocaleProvider/LocaleResolver.php';

        return $container->privates['Ibexa\\ProductCatalog\\NumberFormatter\\LocaleProvider\\LocaleResolver'] = new \Ibexa\ProductCatalog\NumberFormatter\LocaleProvider\LocaleResolver(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
