<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLimitationDenormalizerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\Migration\Serializer\Denormalizer\Action\LimitationDenormalizer' shared autowired service.
     *
     * @return \Ibexa\Bundle\Migration\Serializer\Denormalizer\Action\LimitationDenormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/bundle/Serializer/Denormalizer/Action/LimitationDenormalizer.php';

        return new \Ibexa\Bundle\Migration\Serializer\Denormalizer\Action\LimitationDenormalizer(($container->services['ibexa.api.service.role'] ?? $container->getIbexa_Api_Service_RoleService()), ($container->privates['Ibexa\\Migration\\Generator\\Role\\StepBuilder\\LimitationConverterManager'] ?? $container->load('getLimitationConverterManagerService')));
    }
}
