<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeasurementSimpleOptionsValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Measurement\ProductCatalog\Form\Attribute\MeasurementSimpleOptionsValidator' shared autowired service.
     *
     * @return \Ibexa\Measurement\ProductCatalog\Form\Attribute\MeasurementSimpleOptionsValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/contracts/Local/Attribute/OptionsValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/measurement/src/lib/ProductCatalog/Form/Attribute/AbstractMeasurementOptionsValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/measurement/src/lib/ProductCatalog/Form/Attribute/MeasurementSimpleOptionsValidator.php';

        $a = ($container->services['.container.private.validator'] ?? $container->get_Container_Private_ValidatorService());

        if (isset($container->privates['Ibexa\\Measurement\\ProductCatalog\\Form\\Attribute\\MeasurementSimpleOptionsValidator'])) {
            return $container->privates['Ibexa\\Measurement\\ProductCatalog\\Form\\Attribute\\MeasurementSimpleOptionsValidator'];
        }

        return $container->privates['Ibexa\\Measurement\\ProductCatalog\\Form\\Attribute\\MeasurementSimpleOptionsValidator'] = new \Ibexa\Measurement\ProductCatalog\Form\Attribute\MeasurementSimpleOptionsValidator($a);
    }
}
