<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigrateFlexWorkflowCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Ibexa\Bundle\Workflow\Command\MigrateFlexWorkflowCommand' shared autowired service.
     *
     * @return \Ibexa\Bundle\Workflow\Command\MigrateFlexWorkflowCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/Command/BackwardCompatibleCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/workflow/src/bundle/Command/MigrateFlexWorkflowCommand.php';

        $container->services['console.command.public_alias.Ibexa\\Bundle\\Workflow\\Command\\MigrateFlexWorkflowCommand'] = $instance = new \Ibexa\Bundle\Workflow\Command\MigrateFlexWorkflowCommand(($container->services['ibexa.persistence.connection'] ?? $container->getIbexa_Persistence_ConnectionService()), ($container->privates['Ibexa\\Workflow\\Persistence\\Gateway\\DoctrineGateway'] ?? $container->getDoctrineGateway3Service()));

        $instance->addOption('siteaccess', NULL, 4, 'SiteAccess to use for operations. If not provided, default siteaccess will be used');

        return $instance;
    }
}
