<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMemberTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\CorporateAccount\Form\Type\Member\MemberType' shared autowired service.
     *
     * @return \Ibexa\CorporateAccount\Form\Type\Member\MemberType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/lib/Form/Type/Member/MemberType.php';

        $a = ($container->privates['Ibexa\\CorporateAccount\\Event\\MemberService'] ?? $container->getMemberServiceService());

        if (isset($container->privates['Ibexa\\CorporateAccount\\Form\\Type\\Member\\MemberType'])) {
            return $container->privates['Ibexa\\CorporateAccount\\Form\\Type\\Member\\MemberType'];
        }

        return $container->privates['Ibexa\\CorporateAccount\\Form\\Type\\Member\\MemberType'] = new \Ibexa\CorporateAccount\Form\Type\Member\MemberType($a);
    }
}
