<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaComparisonEngineService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\VersionComparison\Engine\FieldType\MediaComparisonEngine' shared autowired service.
     *
     * @return \Ibexa\VersionComparison\Engine\FieldType\MediaComparisonEngine
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/version-comparison/src/contracts/Engine/FieldTypeComparisonEngine.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/version-comparison/src/lib/Engine/FieldType/MediaComparisonEngine.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/version-comparison/src/lib/Engine/Value/StringComparisonEngine.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/version-comparison/src/lib/Engine/Value/IntegerComparisonEngine.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/version-comparison/src/lib/Engine/Value/BooleanComparisonEngine.php';

        return $container->privates['Ibexa\\VersionComparison\\Engine\\FieldType\\MediaComparisonEngine'] = new \Ibexa\VersionComparison\Engine\FieldType\MediaComparisonEngine(($container->privates['Ibexa\\VersionComparison\\Engine\\Value\\StringComparisonEngine'] ?? ($container->privates['Ibexa\\VersionComparison\\Engine\\Value\\StringComparisonEngine'] = new \Ibexa\VersionComparison\Engine\Value\StringComparisonEngine())), ($container->privates['Ibexa\\VersionComparison\\Engine\\Value\\IntegerComparisonEngine'] ?? ($container->privates['Ibexa\\VersionComparison\\Engine\\Value\\IntegerComparisonEngine'] = new \Ibexa\VersionComparison\Engine\Value\IntegerComparisonEngine())), ($container->privates['Ibexa\\VersionComparison\\Engine\\Value\\BinaryFileComparisonEngine'] ?? $container->load('getBinaryFileComparisonEngine2Service')), ($container->privates['Ibexa\\VersionComparison\\Engine\\Value\\BooleanComparisonEngine'] ?? ($container->privates['Ibexa\\VersionComparison\\Engine\\Value\\BooleanComparisonEngine'] = new \Ibexa\VersionComparison\Engine\Value\BooleanComparisonEngine())));
    }
}
