<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMultiCustomerAccountsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Personalization\Form\Type\MultiCustomerAccountsType' shared autowired service.
     *
     * @return \Ibexa\Personalization\Form\Type\MultiCustomerAccountsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/personalization/src/lib/Form/Type/MultiCustomerAccountsType.php';

        $a = ($container->privates['Ibexa\\Personalization\\Security\\Service\\SecurityService'] ?? $container->load('getSecurityServiceService'));

        if (isset($container->privates['Ibexa\\Personalization\\Form\\Type\\MultiCustomerAccountsType'])) {
            return $container->privates['Ibexa\\Personalization\\Form\\Type\\MultiCustomerAccountsType'];
        }

        return $container->privates['Ibexa\\Personalization\\Form\\Type\\MultiCustomerAccountsType'] = new \Ibexa\Personalization\Form\Type\MultiCustomerAccountsType($a);
    }
}
