<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMemberCustomerGroupResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\CorporateAccount\CustomerGroup\MemberCustomerGroupResolver' shared autowired service.
     *
     * @return \Ibexa\CorporateAccount\CustomerGroup\MemberCustomerGroupResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/lib/CustomerGroup/MemberCustomerGroupResolver.php';

        $a = ($container->privates['Ibexa\\CorporateAccount\\Permission\\MemberResolver'] ?? $container->load('getMemberResolverService'));

        if (isset($container->privates['Ibexa\\CorporateAccount\\CustomerGroup\\MemberCustomerGroupResolver'])) {
            return $container->privates['Ibexa\\CorporateAccount\\CustomerGroup\\MemberCustomerGroupResolver'];
        }
        $b = ($container->privates['Ibexa\\CorporateAccount\\Event\\MemberService'] ?? $container->getMemberServiceService());

        if (isset($container->privates['Ibexa\\CorporateAccount\\CustomerGroup\\MemberCustomerGroupResolver'])) {
            return $container->privates['Ibexa\\CorporateAccount\\CustomerGroup\\MemberCustomerGroupResolver'];
        }
        $c = ($container->privates['Ibexa\\CorporateAccount\\Event\\CompanyService'] ?? $container->getCompanyServiceService());

        if (isset($container->privates['Ibexa\\CorporateAccount\\CustomerGroup\\MemberCustomerGroupResolver'])) {
            return $container->privates['Ibexa\\CorporateAccount\\CustomerGroup\\MemberCustomerGroupResolver'];
        }

        return $container->privates['Ibexa\\CorporateAccount\\CustomerGroup\\MemberCustomerGroupResolver'] = new \Ibexa\CorporateAccount\CustomerGroup\MemberCustomerGroupResolver($a, $b, $c, ($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\CustomerGroupService'] ?? $container->getCustomerGroupServiceService()));
    }
}
