<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Scheduler\ValueObject\NotificationFactory' shared autowired service.
     *
     * @return \Ibexa\Scheduler\ValueObject\NotificationFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/scheduler/src/lib/ValueObject/NotificationFactory.php';

        $a = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['Ibexa\\Scheduler\\ValueObject\\NotificationFactory'])) {
            return $container->privates['Ibexa\\Scheduler\\ValueObject\\NotificationFactory'];
        }
        $b = ($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService());

        if (isset($container->privates['Ibexa\\Scheduler\\ValueObject\\NotificationFactory'])) {
            return $container->privates['Ibexa\\Scheduler\\ValueObject\\NotificationFactory'];
        }
        $c = ($container->services['ibexa.api.service.content_type'] ?? $container->getIbexa_Api_Service_ContentTypeService());

        if (isset($container->privates['Ibexa\\Scheduler\\ValueObject\\NotificationFactory'])) {
            return $container->privates['Ibexa\\Scheduler\\ValueObject\\NotificationFactory'];
        }
        $d = ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService());

        if (isset($container->privates['Ibexa\\Scheduler\\ValueObject\\NotificationFactory'])) {
            return $container->privates['Ibexa\\Scheduler\\ValueObject\\NotificationFactory'];
        }

        return $container->privates['Ibexa\\Scheduler\\ValueObject\\NotificationFactory'] = new \Ibexa\Scheduler\ValueObject\NotificationFactory($a, $b, $c, $d, ($container->privates['Ibexa\\Core\\MVC\\Symfony\\Routing\\Generator\\UrlAliasGenerator'] ?? $container->getUrlAliasGeneratorService()));
    }
}
