<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNameHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\GraphQL\Schema\Domain\Content\NameHelper' shared autowired service.
     *
     * @return \Ibexa\GraphQL\Schema\Domain\Content\NameHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/graphql/src/lib/Schema/Domain/BaseNameHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/graphql/src/lib/Schema/Domain/Content/NameHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/graphql/src/lib/Schema/Domain/Pluralizer.php';

        $a = ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService());

        $container->privates['Ibexa\\GraphQL\\Schema\\Domain\\Content\\NameHelper'] = $instance = new \Ibexa\GraphQL\Schema\Domain\Content\NameHelper($container->parameters['ibexa.graphql.schema.content.field_name.override'], ($container->privates['Ibexa\\GraphQL\\Schema\\Domain\\Pluralizer'] ?? ($container->privates['Ibexa\\GraphQL\\Schema\\Domain\\Pluralizer'] = new \Ibexa\GraphQL\Schema\Domain\Pluralizer())), $a);

        $instance->setLogger($a);

        return $instance;
    }
}
