<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNameSortingDefinitionProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Search\SortingDefinition\Provider\NameSortingDefinitionProvider' shared autowired service.
     *
     * @return \Ibexa\Search\SortingDefinition\Provider\NameSortingDefinitionProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/search/src/contracts/SortingDefinition/SortingDefinitionProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/search/src/lib/SortingDefinition/Provider/NameSortingDefinitionProvider.php';

        return $container->privates['Ibexa\\Search\\SortingDefinition\\Provider\\NameSortingDefinitionProvider'] = new \Ibexa\Search\SortingDefinition\Provider\NameSortingDefinitionProvider(($container->services['Ibexa\\Bundle\\Core\\ApiLoader\\RepositoryConfigurationProvider'] ?? $container->getRepositoryConfigurationProviderService()), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()));
    }
}
