<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOnHoldTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\CorporateAccount\Form\Type\Workflow\OnHoldType' shared autowired service.
     *
     * @return \Ibexa\CorporateAccount\Form\Type\Workflow\OnHoldType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/lib/Form/Type/Workflow/OnHoldType.php';

        $a = ($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService());

        if (isset($container->privates['Ibexa\\CorporateAccount\\Form\\Type\\Workflow\\OnHoldType'])) {
            return $container->privates['Ibexa\\CorporateAccount\\Form\\Type\\Workflow\\OnHoldType'];
        }
        $b = ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService());

        if (isset($container->privates['Ibexa\\CorporateAccount\\Form\\Type\\Workflow\\OnHoldType'])) {
            return $container->privates['Ibexa\\CorporateAccount\\Form\\Type\\Workflow\\OnHoldType'];
        }

        return $container->privates['Ibexa\\CorporateAccount\\Form\\Type\\Workflow\\OnHoldType'] = new \Ibexa\CorporateAccount\Form\Type\Workflow\OnHoldType(($container->privates['Ibexa\\CorporateAccount\\Configuration\\CorporateAccount'] ?? $container->getCorporateAccountService()), $a, $b);
    }
}
