<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\FieldTypePage\GraphQL\Resolver\PageResolver' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\GraphQL\Resolver\PageResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/GraphQL/Resolver/PageResolver.php';

        $a = ($container->services['overblog_graphql.type_resolver'] ?? $container->load('getOverblogGraphql_TypeResolverService'));

        if (isset($container->privates['Ibexa\\FieldTypePage\\GraphQL\\Resolver\\PageResolver'])) {
            return $container->privates['Ibexa\\FieldTypePage\\GraphQL\\Resolver\\PageResolver'];
        }

        return $container->privates['Ibexa\\FieldTypePage\\GraphQL\\Resolver\\PageResolver'] = new \Ibexa\FieldTypePage\GraphQL\Resolver\PageResolver($a, ['qualifio' => 'QualifioPageBlock', 'ibexa_news' => 'IbexaNewsPageBlock', 'quick_actions' => 'QuickActionsPageBlock', 'my_content' => 'MyContentPageBlock', 'common_content' => 'CommonContentPageBlock', 'review_queue' => 'ReviewQueuePageBlock', 'ibexa_activity_log_list' => 'IbexaActivityLogListPageBlock', 'sales_rep' => 'SalesRepPageBlock', 'targeting' => 'TargetingPageBlock', 'form' => 'FormPageBlock', 'tag' => 'TagPageBlock', 'contentlist' => 'ContentlistPageBlock', 'banner' => 'BannerPageBlock', 'collection' => 'CollectionPageBlock', 'embed' => 'EmbedPageBlock', 'gallery' => 'GalleryPageBlock', 'video' => 'VideoPageBlock', 'rss' => 'RssPageBlock', 'schedule' => 'SchedulePageBlock', 'richtext' => 'RichtextPageBlock', 'catalog' => 'CatalogPageBlock', 'product_collection' => 'ProductCollectionPageBlock', 'products_with_lowest_stock' => 'ProductsWithLowestStockPageBlock', 'products_by_categories' => 'ProductsByCategoriesPageBlock', 'personalized' => 'PersonalizedPageBlock', 'dynamic_targeting' => 'DynamicTargetingPageBlock', 'last_viewed' => 'LastViewedPageBlock', 'last_purchased' => 'LastPurchasedPageBlock', 'bestsellers' => 'BestsellersPageBlock', 'recently_added' => 'RecentlyAddedPageBlock', 'top_clicked_items' => 'TopClickedItemsPageBlock', 'ibexa_connect_block' => 'IbexaConnectBlockPageBlock']);
    }
}
