<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreviewTabService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\SiteContext\UI\Tabs\PreviewTab' shared autowired service.
     *
     * @return \Ibexa\Bundle\SiteContext\UI\Tabs\PreviewTab
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/TabInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/AbstractTab.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/AbstractEventDispatchingTab.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/ConditionalTabInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Tab/OrderedTabInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/site-context/src/bundle/UI/Tabs/PreviewTab.php';

        $a = ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService());

        if (isset($container->services['Ibexa\\Bundle\\SiteContext\\UI\\Tabs\\PreviewTab'])) {
            return $container->services['Ibexa\\Bundle\\SiteContext\\UI\\Tabs\\PreviewTab'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['Ibexa\\Bundle\\SiteContext\\UI\\Tabs\\PreviewTab'])) {
            return $container->services['Ibexa\\Bundle\\SiteContext\\UI\\Tabs\\PreviewTab'];
        }

        return $container->services['Ibexa\\Bundle\\SiteContext\\UI\\Tabs\\PreviewTab'] = new \Ibexa\Bundle\SiteContext\UI\Tabs\PreviewTab($a, ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()), $b, ($container->privates['Ibexa\\SiteContext\\SiteContextService'] ?? $container->getSiteContextServiceService()), ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()));
    }
}
