<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilerController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Overblog\GraphQLBundle\Controller\ProfilerController' shared service.
     *
     * @return \Overblog\GraphQLBundle\Controller\ProfilerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Controller/ProfilerController.php';

        return $container->services['Overblog\\GraphQLBundle\\Controller\\ProfilerController'] = new \Overblog\GraphQLBundle\Controller\ProfilerController(($container->services['.container.private.profiler'] ?? $container->get_Container_Private_ProfilerService()), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['router'] ?? $container->getRouterService()), ($container->services['overblog_graphql.request_executor'] ?? $container->load('getOverblogGraphql_RequestExecutorService')), NULL);
    }
}
