<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreviewUrlRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\SiteContext\Twig\PreviewUrlRuntime' shared autowired service.
     *
     * @return \Ibexa\Bundle\SiteContext\Twig\PreviewUrlRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/site-context/src/bundle/Twig/PreviewUrlRuntime.php';

        $a = ($container->privates['Ibexa\\SiteContext\\PreviewUrlResolver\\LocationPreviewUrlResolver'] ?? $container->load('getLocationPreviewUrlResolverService'));

        if (isset($container->privates['Ibexa\\Bundle\\SiteContext\\Twig\\PreviewUrlRuntime'])) {
            return $container->privates['Ibexa\\Bundle\\SiteContext\\Twig\\PreviewUrlRuntime'];
        }

        return $container->privates['Ibexa\\Bundle\\SiteContext\\Twig\\PreviewUrlRuntime'] = new \Ibexa\Bundle\SiteContext\Twig\PreviewUrlRuntime($a);
    }
}
