<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPresentationFormattingStrategyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Measurement\Formatter\Strategy\PresentationFormattingStrategy' shared autowired service.
     *
     * @return \Ibexa\Measurement\Formatter\Strategy\PresentationFormattingStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/measurement/src/lib/Formatter/Strategy/FormattingStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/measurement/src/lib/Formatter/Strategy/PresentationFormattingStrategy.php';

        return $container->privates['Ibexa\\Measurement\\Formatter\\Strategy\\PresentationFormattingStrategy'] = new \Ibexa\Measurement\Formatter\Strategy\PresentationFormattingStrategy(($container->privates['Ibexa\\ProductCatalog\\NumberFormatter\\NumberFormatterFactory'] ?? $container->load('getNumberFormatterFactoryService')));
    }
}
