<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageBuilderTemplatesSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Scheduler\Event\Subscriber\PageBuilderTemplatesSubscriber' shared autowired service.
     *
     * @return \Ibexa\Scheduler\Event\Subscriber\PageBuilderTemplatesSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/scheduler/src/lib/Event/Subscriber/PageBuilderTemplatesSubscriber.php';

        $a = ($container->privates['Ibexa\\Scheduler\\Repository\\DateBasedPublisherService'] ?? $container->load('getDateBasedPublisherServiceService'));

        if (isset($container->privates['Ibexa\\Scheduler\\Event\\Subscriber\\PageBuilderTemplatesSubscriber'])) {
            return $container->privates['Ibexa\\Scheduler\\Event\\Subscriber\\PageBuilderTemplatesSubscriber'];
        }

        return $container->privates['Ibexa\\Scheduler\\Event\\Subscriber\\PageBuilderTemplatesSubscriber'] = new \Ibexa\Scheduler\Event\Subscriber\PageBuilderTemplatesSubscriber($a);
    }
}
