<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPolicyTranslationExtractorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\AdminUi\Translation\Extractor\PolicyTranslationExtractor' shared autowired service.
     *
     * @return \Ibexa\AdminUi\Translation\Extractor\PolicyTranslationExtractor
     *
     * @deprecated Since ibexa/admin-ui 4.4: The "Ibexa\AdminUi\Translation\Extractor\PolicyTranslationExtractor" service is deprecated, will be removed in 5.0
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('', '', 'Since ibexa/admin-ui 4.4: The "Ibexa\\AdminUi\\Translation\\Extractor\\PolicyTranslationExtractor" service is deprecated, will be removed in 5.0');

        return new \Ibexa\AdminUi\Translation\Extractor\PolicyTranslationExtractor($container->parameters['ibexa.api.role.policy_map']);
    }
}
