<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductPriceCreateStepExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ProductCatalog\Migrations\ProductPrice\ProductPriceCreateStepExecutor' shared autowired service.
     *
     * @return \Ibexa\ProductCatalog\Migrations\ProductPrice\ProductPriceCreateStepExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/StepExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/UserContextAwareStepExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/service-contracts/ServiceSubscriberTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/UserContextAwareStepExecutorTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/contracts/StepExecutor/AbstractStepExecutor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/Migrations/ProductPrice/ProductPriceCreateStepExecutor.php';

        $container->privates['Ibexa\\ProductCatalog\\Migrations\\ProductPrice\\ProductPriceCreateStepExecutor'] = $instance = new \Ibexa\ProductCatalog\Migrations\ProductPrice\ProductPriceCreateStepExecutor(($container->privates['Ibexa\\ProductCatalog\\Dispatcher\\ProductServiceDispatcher'] ?? $container->getProductServiceDispatcherService()), ($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\Event\\CurrencyService'] ?? $container->getCurrencyServiceService()), ($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\CustomerGroupService'] ?? $container->getCustomerGroupServiceService()), ($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\Event\\ProductPriceService'] ?? $container->getProductPriceServiceService()));

        $instance->setContainer(($container->privates['.service_locator.A.yU1Hk'] ?? $container->load('get_ServiceLocator_A_YU1HkService'))->withContext('Ibexa\\ProductCatalog\\Migrations\\ProductPrice\\ProductPriceCreateStepExecutor', $container));

        return $instance;
    }
}
