<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPutBlockOntoPageActionExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\FieldTypePage\Migration\Action\PutBlockOntoPage\PutBlockOntoPageActionExecutor' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\Migration\Action\PutBlockOntoPage\PutBlockOntoPageActionExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ActionExecutor/ExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/Migration/Action/PutBlockOntoPage/PutBlockOntoPageActionExecutor.php';

        return $container->privates['Ibexa\\FieldTypePage\\Migration\\Action\\PutBlockOntoPage\\PutBlockOntoPageActionExecutor'] = new \Ibexa\FieldTypePage\Migration\Action\PutBlockOntoPage\PutBlockOntoPageActionExecutor(($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService()));
    }
}
