<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurgeFormSubmissionsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\FormBuilder\Command\PurgeFormSubmissionsCommand' shared autowired service.
     *
     * @return \Ibexa\Bundle\FormBuilder\Command\PurgeFormSubmissionsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/bundle/Command/PurgeFormSubmissionsCommand.php';

        $container->services['Ibexa\\Bundle\\FormBuilder\\Command\\PurgeFormSubmissionsCommand'] = $instance = new \Ibexa\Bundle\FormBuilder\Command\PurgeFormSubmissionsCommand(($container->services['ibexa.api.repository'] ?? $container->getIbexa_Api_RepositoryService()), ($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService()), ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService()), ($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService()), ($container->services['Ibexa\\FormBuilder\\FormSubmission\\FormSubmissionService'] ?? $container->load('getFormSubmissionServiceService')));

        $instance->addOption('siteaccess', NULL, 4, 'SiteAccess to use for operations. If not provided, default siteaccess will be used');
        $instance->setName('ibexa:form-builder:purge-form-submissions');

        return $instance;
    }
}
