<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductAvailabilityStrategyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ProductCatalog\Local\Repository\ProductAvailabilityStrategy' shared autowired service.
     *
     * @return \Ibexa\ProductCatalog\Local\Repository\ProductAvailabilityStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/contracts/ProductAvailabilityStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/Local/Repository/ProductAvailabilityStrategy.php';

        return $container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\ProductAvailabilityStrategy'] = new \Ibexa\ProductCatalog\Local\Repository\ProductAvailabilityStrategy(($container->privates['Ibexa\\ProductCatalog\\Local\\Persistence\\Legacy\\ProductAvailability\\Handler'] ?? $container->getHandler5Service()));
    }
}
