<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageFormMapperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FieldTypePage\FieldType\Page\Mapper\PageFormMapper' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\FieldType\Page\Mapper\PageFormMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/contracts/FieldType/FieldValueFormMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/FieldType/Page/Mapper/PageFormMapper.php';

        return $container->services['Ibexa\\FieldTypePage\\FieldType\\Page\\Mapper\\PageFormMapper'] = new \Ibexa\FieldTypePage\FieldType\Page\Mapper\PageFormMapper();
    }
}
