<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductTypeRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\ProductCatalog\Twig\ProductTypeRuntime' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Twig\ProductTypeRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Twig/ProductTypeRuntime.php';

        return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Twig\\ProductTypeRuntime'] = new \Ibexa\Bundle\ProductCatalog\Twig\ProductTypeRuntime(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()));
    }
}
