<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductActionDispatcherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\ProductCatalog\Form\ActionDispatcher\ProductActionDispatcher' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Form\ActionDispatcher\ProductActionDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/lib/Form/ActionDispatcher/ActionDispatcherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/lib/Form/ActionDispatcher/AbstractActionDispatcher.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Form/ActionDispatcher/ProductActionDispatcher.php';

        $container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\ActionDispatcher\\ProductActionDispatcher'] = $instance = new \Ibexa\Bundle\ProductCatalog\Form\ActionDispatcher\ProductActionDispatcher();

        $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        return $instance;
    }
}
