<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductPriceMapperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\ProductCatalog\Form\DataMapper\ProductPrice\ProductPriceMapper' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Form\DataMapper\ProductPrice\ProductPriceMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Form/DataMapper/ProductPrice/ProductPriceMapper.php';

        return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\DataMapper\\ProductPrice\\ProductPriceMapper'] = new \Ibexa\Bundle\ProductCatalog\Form\DataMapper\ProductPrice\ProductPriceMapper(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\DataMapper\\ProductPrice\\Delete\\BaseDataToStructTransformer'] ?? ($container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\DataMapper\\ProductPrice\\Delete\\BaseDataToStructTransformer'] = new \Ibexa\Bundle\ProductCatalog\Form\DataMapper\ProductPrice\Delete\BaseDataToStructTransformer()));
            yield 1 => ($container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\DataMapper\\ProductPrice\\Create\\BaseDataToStructTransformer'] ?? $container->load('getBaseDataToStructTransformerService'));
            yield 2 => ($container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\DataMapper\\ProductPrice\\Create\\CustomerGroupDataToStructTransformer'] ?? $container->load('getCustomerGroupDataToStructTransformerService'));
            yield 3 => ($container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\DataMapper\\ProductPrice\\Update\\BaseDataToStructTransformer'] ?? $container->load('getBaseDataToStructTransformer3Service'));
        }, 4));
    }
}
