<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Core\MVC\Symfony\Controller\Content\QueryController' shared service.
     *
     * @return \Ibexa\Core\MVC\Symfony\Controller\Content\QueryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/Controller/Content/QueryController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/QueryType/ContentViewQueryTypeMapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/QueryType/QueryParameterContentViewQueryTypeMapper.php';

        return $container->services['Ibexa\\Core\\MVC\\Symfony\\Controller\\Content\\QueryController'] = new \Ibexa\Core\MVC\Symfony\Controller\Content\QueryController(new \Ibexa\Core\QueryType\QueryParameterContentViewQueryTypeMapper(($container->privates['Ibexa\\Core\\QueryType\\ArrayQueryTypeRegistry'] ?? $container->getArrayQueryTypeRegistryService())), ($container->services['ibexa.api.service.search'] ?? $container->getIbexa_Api_Service_SearchService()));
    }
}
