<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueryFieldResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\FieldTypeQuery\GraphQL\QueryFieldResolver' shared autowired service.
     *
     * @return \Ibexa\FieldTypeQuery\GraphQL\QueryFieldResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-query/src/lib/GraphQL/QueryFieldResolver.php';

        return $container->privates['Ibexa\\FieldTypeQuery\\GraphQL\\QueryFieldResolver'] = new \Ibexa\FieldTypeQuery\GraphQL\QueryFieldResolver(($container->services['Ibexa\\FieldTypeQuery\\QueryFieldService'] ?? $container->load('getQueryFieldServiceService')));
    }
}
