<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepeatableStepExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Migration\StepExecutor\RepeatableStepExecutor' shared autowired service.
     *
     * @return \Ibexa\Migration\StepExecutor\RepeatableStepExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/StepExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/UserContextAwareStepExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/service-contracts/ServiceSubscriberTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/UserContextAwareStepExecutorTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/contracts/StepExecutor/AbstractStepExecutor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Log/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/RepeatableStepExecutor.php';

        $a = ($container->privates['Ibexa\\Migration\\StepExecutor\\StepExecutorManager'] ?? $container->load('getStepExecutorManagerService'));

        if (isset($container->privates['Ibexa\\Migration\\StepExecutor\\RepeatableStepExecutor'])) {
            return $container->privates['Ibexa\\Migration\\StepExecutor\\RepeatableStepExecutor'];
        }

        $container->privates['Ibexa\\Migration\\StepExecutor\\RepeatableStepExecutor'] = $instance = new \Ibexa\Migration\StepExecutor\RepeatableStepExecutor($a);

        $instance->setPermissionResolver(($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService()));
        $instance->setContainer(($container->privates['.service_locator.A.yU1Hk'] ?? $container->load('get_ServiceLocator_A_YU1HkService'))->withContext('Ibexa\\Migration\\StepExecutor\\RepeatableStepExecutor', $container));

        return $instance;
    }
}
