<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestKernelViewSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\HttpCache\EventSubscriber\RestKernelViewSubscriber' shared service.
     *
     * @return \Ibexa\HttpCache\EventSubscriber\RestKernelViewSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/http-cache/src/lib/EventSubscriber/RestKernelViewSubscriber.php';

        return $container->privates['Ibexa\\HttpCache\\EventSubscriber\\RestKernelViewSubscriber'] = new \Ibexa\HttpCache\EventSubscriber\RestKernelViewSubscriber(($container->services['FOS\\HttpCacheBundle\\Http\\SymfonyResponseTagger'] ?? $container->getSymfonyResponseTaggerService()));
    }
}
