<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRichTextBlockSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\FieldTypePage\Event\Subscriber\RichTextBlockSubscriber' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\Event\Subscriber\RichTextBlockSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/Event/Subscriber/RichTextBlockSubscriber.php';

        return $container->services['Ibexa\\FieldTypePage\\Event\\Subscriber\\RichTextBlockSubscriber'] = new \Ibexa\FieldTypePage\Event\Subscriber\RichTextBlockSubscriber(($container->privates['Ibexa\\FieldTypeRichText\\RichText\\DOMDocumentFactory'] ?? ($container->privates['Ibexa\\FieldTypeRichText\\RichText\\DOMDocumentFactory'] = new \Ibexa\FieldTypeRichText\RichText\DOMDocumentFactory())));
    }
}
