<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenderProductCompletenessRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\ProductCatalog\Twig\RenderProductCompletenessRuntime' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Twig\RenderProductCompletenessRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Twig/RenderProductCompletenessRuntime.php';

        $a = ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService());

        if (isset($container->privates['Ibexa\\Bundle\\ProductCatalog\\Twig\\RenderProductCompletenessRuntime'])) {
            return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Twig\\RenderProductCompletenessRuntime'];
        }

        return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Twig\\RenderProductCompletenessRuntime'] = new \Ibexa\Bundle\ProductCatalog\Twig\RenderProductCompletenessRuntime(($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()), $a);
    }
}
