<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResizeOriginalImagesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Ibexa\Bundle\Core\Command\ResizeOriginalImagesCommand' shared autowired service.
     *
     * @return \Ibexa\Bundle\Core\Command\ResizeOriginalImagesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/Command/BackwardCompatibleCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/Command/ResizeOriginalImagesCommand.php';

        $container->services['console.command.public_alias.Ibexa\\Bundle\\Core\\Command\\ResizeOriginalImagesCommand'] = $instance = new \Ibexa\Bundle\Core\Command\ResizeOriginalImagesCommand(($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService()), ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService()), ($container->services['ibexa.api.service.content_type'] ?? $container->getIbexa_Api_Service_ContentTypeService()), ($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService()), ($container->services['ibexa.api.service.search'] ?? $container->getIbexa_Api_Service_SearchService()), ($container->services['liip_imagine.filter.manager'] ?? $container->getLiipImagine_Filter_ManagerService()), ($container->privates['ibexa.field_type.ezimage.io_service.published.config_scope_change_aware'] ?? $container->getIbexa_FieldType_Ezimage_IoService_Published_ConfigScopeChangeAwareService()), ($container->privates['mime_types'] ?? $container->getMimeTypesService()), ($container->privates['liip_imagine.gd'] ?? $container->getLiipImagine_GdService()));

        $instance->addOption('siteaccess', NULL, 4, 'SiteAccess to use for operations. If not provided, default siteaccess will be used');

        return $instance;
    }
}
