<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestBlockConfigurationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\PageBuilder\Form\Type\Block\RequestBlockConfigurationType' shared autowired service.
     *
     * @return \Ibexa\PageBuilder\Form\Type\Block\RequestBlockConfigurationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/page-builder/src/lib/Form/Type/Block/RequestBlockConfigurationType.php';

        return $container->services['Ibexa\\PageBuilder\\Form\\Type\\Block\\RequestBlockConfigurationType'] = new \Ibexa\PageBuilder\Form\Type\Block\RequestBlockConfigurationType();
    }
}
