<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRichtextBlockAttributeTypeResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\FieldTypePage\GraphQL\Resolver\RichtextBlockAttributeTypeResolver' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\GraphQL\Resolver\RichtextBlockAttributeTypeResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/GraphQL/Resolver/RichtextBlockAttributeTypeResolver.php';

        return $container->privates['Ibexa\\FieldTypePage\\GraphQL\\Resolver\\RichtextBlockAttributeTypeResolver'] = new \Ibexa\FieldTypePage\GraphQL\Resolver\RichtextBlockAttributeTypeResolver(($container->privates['ibexa.richtext.converter.output.xhtml5'] ?? $container->getIbexa_Richtext_Converter_Output_Xhtml5Service()), ($container->privates['Ibexa\\FieldTypeRichText\\RichText\\Converter\\Html5Edit'] ?? $container->getHtml5EditService()));
    }
}
