<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommendationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\Personalization\Controller\RecommendationController' shared autowired service.
     *
     * @return \Ibexa\Bundle\Personalization\Controller\RecommendationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/personalization/src/bundle/Controller/RecommendationController.php';

        $container->services['Ibexa\\Bundle\\Personalization\\Controller\\RecommendationController'] = $instance = new \Ibexa\Bundle\Personalization\Controller\RecommendationController(($container->privates['Ibexa\\Personalization\\Config\\PersonalizationClientCredentialsResolver'] ?? $container->getPersonalizationClientCredentialsResolverService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['webpack_encore.tag_renderer'] ?? $container->load('getWebpackEncore_TagRendererService')), ($container->privates['webpack_encore.entrypoint_lookup_collection'] ?? $container->getWebpackEncore_EntrypointLookupCollectionService()), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Ibexa\\Bundle\\Personalization\\Controller\\RecommendationController', $container));

        return $instance;
    }
}
