<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleDeleteStepExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Migration\StepExecutor\RoleDeleteStepExecutor' shared autowired service.
     *
     * @return \Ibexa\Migration\StepExecutor\RoleDeleteStepExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/StepExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Log/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/RoleDeleteStepExecutor.php';

        return $container->privates['Ibexa\\Migration\\StepExecutor\\RoleDeleteStepExecutor'] = new \Ibexa\Migration\StepExecutor\RoleDeleteStepExecutor(($container->privates['Ibexa\\Core\\Persistence\\Cache\\TransactionHandler'] ?? $container->getTransactionHandlerService()), ($container->services['ibexa.api.service.role'] ?? $container->getIbexa_Api_Service_RoleService()), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
    }
}
