<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRootControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\CorporateAccount\Controller\REST\RootController' shared autowired service.
     *
     * @return \Ibexa\Bundle\CorporateAccount\Controller\REST\RootController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/rest/src/lib/Server/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/corporate-account/src/bundle/Controller/REST/RootController.php';

        return $container->services['Ibexa\\Bundle\\CorporateAccount\\Controller\\REST\\RootController'] = new \Ibexa\Bundle\CorporateAccount\Controller\REST\RootController(($container->privates['Ibexa\\CorporateAccount\\Configuration\\CorporateAccount'] ?? $container->getCorporateAccountService()), ($container->services['ibexa.api.service.content_type'] ?? $container->getIbexa_Api_Service_ContentTypeService()), ($container->services['ibexa.api.service.role'] ?? $container->getIbexa_Api_Service_RoleService()));
    }
}
