<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Rest\Server\Controller\Role' shared autowired service.
     *
     * @return \Ibexa\Rest\Server\Controller\Role
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/rest/src/lib/Server/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/rest/src/lib/Server/Controller/Role.php';

        $container->services['Ibexa\\Rest\\Server\\Controller\\Role'] = $instance = new \Ibexa\Rest\Server\Controller\Role(($container->services['ibexa.api.service.role'] ?? $container->getIbexa_Api_Service_RoleService()), ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService()), ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService()));

        $instance->setContainer($container);
        $instance->setInputDispatcher(($container->privates['Ibexa\\Rest\\Input\\Dispatcher'] ?? $container->getDispatcherService()));
        $instance->setRouter(($container->services['router'] ?? $container->getRouterService()));
        $instance->setRequestParser(($container->privates['Ibexa\\Bundle\\Rest\\RequestParser\\Router'] ?? $container->getRouter2Service()));
        $instance->setRepository(($container->services['ibexa.api.repository'] ?? $container->getIbexa_Api_RepositoryService()));

        return $instance;
    }
}
