<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSelectionValueFormMapperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\ProductCatalog\Form\Attribute\SelectionValueFormMapper' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Form\Attribute\SelectionValueFormMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/contracts/Local/Attribute/ValueFormMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Form/Attribute/SelectionValueFormMapper.php';

        return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Form\\Attribute\\SelectionValueFormMapper'] = new \Ibexa\Bundle\ProductCatalog\Form\Attribute\SelectionValueFormMapper(($container->privates['Ibexa\\Bundle\\Core\\SiteAccess\\LanguageResolver'] ?? $container->getLanguageResolverService()));
    }
}
