<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSectionUpdateTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\AdminUi\Form\Type\Section\SectionUpdateType' shared autowired service.
     *
     * @return \Ibexa\AdminUi\Form\Type\Section\SectionUpdateType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Form/Type/Section/SectionUpdateType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Form/Type/Section/SectionType.php';

        return $container->privates['Ibexa\\AdminUi\\Form\\Type\\Section\\SectionUpdateType'] = new \Ibexa\AdminUi\Form\Type\Section\SectionUpdateType(($container->privates['Ibexa\\AdminUi\\Form\\Type\\Section\\SectionType'] ?? ($container->privates['Ibexa\\AdminUi\\Form\\Type\\Section\\SectionType'] = new \Ibexa\AdminUi\Form\Type\Section\SectionType())));
    }
}
