<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSiteAccessListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\Core\EventListener\SiteAccessListener' shared service.
     *
     * @return \Ibexa\Bundle\Core\EventListener\SiteAccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/EventListener/SiteAccessListener.php';

        return $container->privates['Ibexa\\Bundle\\Core\\EventListener\\SiteAccessListener'] = new \Ibexa\Bundle\Core\EventListener\SiteAccessListener(($container->privates['Ibexa\\Core\\MVC\\Symfony\\SiteAccess'] ?? ($container->privates['Ibexa\\Core\\MVC\\Symfony\\SiteAccess'] = new \Ibexa\Core\MVC\Symfony\SiteAccess('default', 'uninitialized'))));
    }
}
