<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSortingDefinitionChoiceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\Search\Form\Type\SortingDefinitionChoiceType' shared service.
     *
     * @return \Ibexa\Bundle\Search\Form\Type\SortingDefinitionChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/search/src/bundle/Form/Type/SortingDefinitionChoiceType.php';

        return $container->privates['Ibexa\\Bundle\\Search\\Form\\Type\\SortingDefinitionChoiceType'] = new \Ibexa\Bundle\Search\Form\Type\SortingDefinitionChoiceType(($container->privates['Ibexa\\Search\\SortingDefinition\\SortingDefinitionRegistry'] ?? $container->getSortingDefinitionRegistryService()));
    }
}
