<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShortDateTimeFormatTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\User\Form\Type\UserSettings\ShortDateTimeFormatType' shared autowired service.
     *
     * @return \Ibexa\User\Form\Type\UserSettings\ShortDateTimeFormatType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/user/src/lib/Form/Type/UserSettings/ShortDateTimeFormatType.php';

        return $container->privates['Ibexa\\User\\Form\\Type\\UserSettings\\ShortDateTimeFormatType'] = new \Ibexa\User\Form\Type\UserSettings\ShortDateTimeFormatType(($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()));
    }
}
