<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSectionCreateStepExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Migration\StepExecutor\SectionCreateStepExecutor' shared autowired service.
     *
     * @return \Ibexa\Migration\StepExecutor\SectionCreateStepExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/StepExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/UserContextAwareStepExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/service-contracts/ServiceSubscriberTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/UserContextAwareStepExecutorTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/contracts/StepExecutor/AbstractStepExecutor.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/Log/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/SectionCreateStepExecutor.php';

        $container->privates['Ibexa\\Migration\\StepExecutor\\SectionCreateStepExecutor'] = $instance = new \Ibexa\Migration\StepExecutor\SectionCreateStepExecutor(($container->privates['Ibexa\\Core\\Persistence\\Cache\\TransactionHandler'] ?? $container->getTransactionHandlerService()), ($container->services['ibexa.api.service.section'] ?? $container->getIbexa_Api_Service_SectionService()), ($container->privates['Ibexa\\Migration\\StepExecutor\\ActionExecutor\\Section\\Executor'] ?? $container->load('getExecutor2Service')), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        $instance->setPermissionResolver(($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService()));
        $instance->setContainer(($container->privates['.service_locator.YS.oPHg'] ?? $container->load('get_ServiceLocator_YS_OPHgService'))->withContext('Ibexa\\Migration\\StepExecutor\\SectionCreateStepExecutor', $container));

        return $instance;
    }
}
