<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubtreeLimitationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Core\Limitation\SubtreeLimitationType' shared service.
     *
     * @return \Ibexa\Core\Limitation\SubtreeLimitationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/Limitation/AbstractPersistenceLimitationType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/contracts/Limitation/Type.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/Limitation/SubtreeLimitationType.php';

        $a = ($container->privates['Ibexa\\Core\\Persistence\\Cache\\Handler'] ?? $container->getHandler2Service());

        if (isset($container->privates['Ibexa\\Core\\Limitation\\SubtreeLimitationType'])) {
            return $container->privates['Ibexa\\Core\\Limitation\\SubtreeLimitationType'];
        }

        return $container->privates['Ibexa\\Core\\Limitation\\SubtreeLimitationType'] = new \Ibexa\Core\Limitation\SubtreeLimitationType($a);
    }
}
