<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchEngineServiceInfoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\SystemInfo\Service\SearchEngineServiceInfo' shared service.
     *
     * @return \Ibexa\SystemInfo\Service\SearchEngineServiceInfo
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/Service/ServiceInfo.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/Service/SearchEngineServiceInfo.php';

        return $container->privates['Ibexa\\SystemInfo\\Service\\SearchEngineServiceInfo'] = new \Ibexa\SystemInfo\Service\SearchEngineServiceInfo(($container->services['Ibexa\\Bundle\\Core\\ApiLoader\\RepositoryConfigurationProvider'] ?? $container->getRepositoryConfigurationProviderService()));
    }
}
