<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSegmentGroupCreateTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Segmentation\Form\Type\SegmentGroupCreateType' shared autowired service.
     *
     * @return \Ibexa\Segmentation\Form\Type\SegmentGroupCreateType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/segmentation/src/lib/Form/Type/SegmentGroupCreateType.php';

        return $container->privates['Ibexa\\Segmentation\\Form\\Type\\SegmentGroupCreateType'] = new \Ibexa\Segmentation\Form\Type\SegmentGroupCreateType();
    }
}
