<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchedulerBlockResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\FieldTypePage\GraphQL\Resolver\SchedulerBlockResolver' shared autowired service.
     *
     * @return \Ibexa\FieldTypePage\GraphQL\Resolver\SchedulerBlockResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/fieldtype-page/src/lib/GraphQL/Resolver/SchedulerBlockResolver.php';

        $a = ($container->services['overblog_graphql.type_resolver'] ?? $container->load('getOverblogGraphql_TypeResolverService'));

        if (isset($container->privates['Ibexa\\FieldTypePage\\GraphQL\\Resolver\\SchedulerBlockResolver'])) {
            return $container->privates['Ibexa\\FieldTypePage\\GraphQL\\Resolver\\SchedulerBlockResolver'];
        }

        return $container->privates['Ibexa\\FieldTypePage\\GraphQL\\Resolver\\SchedulerBlockResolver'] = new \Ibexa\FieldTypePage\GraphQL\Resolver\SchedulerBlockResolver($a);
    }
}
