<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemInfoCollectorRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\SystemInfo\SystemInfo\SystemInfoCollectorRegistry' shared service.
     *
     * @return \Ibexa\Bundle\SystemInfo\SystemInfo\Registry\IdentifierBased
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/bundle/SystemInfo/SystemInfoCollectorRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/bundle/SystemInfo/Registry/IdentifierBased.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/bundle/SystemInfo/Collector/SystemInfoCollector.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/bundle/SystemInfo/Collector/JsonComposerLockSystemInfoCollector.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/VersionStability/VersionStabilityChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/VersionStability/ComposerVersionStabilityChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/bundle/SystemInfo/Collector/EzcHardwareSystemInfoCollector.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/bundle/SystemInfo/Collector/EzcPhpSystemInfoCollector.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/bundle/SystemInfo/Collector/ConfigurationSymfonyKernelSystemInfoCollector.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/bundle/SystemInfo/Collector/ServicesSystemInfoCollector.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/Service/ServiceProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/Service/AggregateServiceProvider.php';

        $a = new \Ibexa\Bundle\SystemInfo\SystemInfo\Collector\JsonComposerLockSystemInfoCollector(new \Ibexa\SystemInfo\VersionStability\ComposerVersionStabilityChecker(), (\dirname(__DIR__, 4).'/composer.lock'), (\dirname(__DIR__, 4).'/composer.json'));
        $b = ($container->privates['Ibexa\\Bundle\\SystemInfo\\SystemInfo\\EzcSystemInfoWrapper'] ?? $container->load('getEzcSystemInfoWrapperService'));

        return $container->services['Ibexa\\Bundle\\SystemInfo\\SystemInfo\\SystemInfoCollectorRegistry'] = new \Ibexa\Bundle\SystemInfo\SystemInfo\Registry\IdentifierBased(['ibexa' => new \Ibexa\Bundle\SystemInfo\SystemInfo\Collector\IbexaSystemInfoCollector($a, \dirname(__DIR__, 4), true), 'composer' => $a, 'repository' => ($container->privates['Ibexa\\Bundle\\SystemInfo\\SystemInfo\\Collector\\RepositorySystemInfoCollector'] ?? $container->load('getRepositorySystemInfoCollectorService')), 'hardware' => new \Ibexa\Bundle\SystemInfo\SystemInfo\Collector\EzcHardwareSystemInfoCollector($b), 'php' => new \Ibexa\Bundle\SystemInfo\SystemInfo\Collector\EzcPhpSystemInfoCollector($b), 'symfony_kernel' => new \Ibexa\Bundle\SystemInfo\SystemInfo\Collector\ConfigurationSymfonyKernelSystemInfoCollector(($container->services['kernel'] ?? $container->get('kernel', 1)), $container->parameters['kernel.bundles']), 'services' => new \Ibexa\Bundle\SystemInfo\SystemInfo\Collector\ServicesSystemInfoCollector(new \Ibexa\SystemInfo\Service\AggregateServiceProvider(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'httpCacheProxy' => ['privates', 'Ibexa\\SystemInfo\\Service\\HttpCacheServiceInfo', 'getHttpCacheServiceInfoService', true],
            'persistenceCacheAdapter' => ['privates', 'Ibexa\\SystemInfo\\Service\\PersistenceCacheServiceInfo', 'getPersistenceCacheServiceInfoService', true],
            'searchEngine' => ['privates', 'Ibexa\\SystemInfo\\Service\\SearchEngineServiceInfo', 'getSearchEngineServiceInfoService', true],
        ], [
            'httpCacheProxy' => 'Ibexa\\SystemInfo\\Service\\HttpCacheServiceInfo',
            'persistenceCacheAdapter' => 'Ibexa\\SystemInfo\\Service\\PersistenceCacheServiceInfo',
            'searchEngine' => 'Ibexa\\SystemInfo\\Service\\SearchEngineServiceInfo',
        ])))]);
    }
}
