<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetViewParametersListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\AdminUi\EventListener\SetViewParametersListener' shared autowired service.
     *
     * @return \Ibexa\AdminUi\EventListener\SetViewParametersListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/EventListener/SetViewParametersListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/contracts/Content/Form/Provider/GroupedContentFormFieldsProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Form/Provider/GroupedNonMetaFormFieldsProvider.php';

        $a = ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService());

        if (isset($container->privates['Ibexa\\AdminUi\\EventListener\\SetViewParametersListener'])) {
            return $container->privates['Ibexa\\AdminUi\\EventListener\\SetViewParametersListener'];
        }
        $b = ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService());

        if (isset($container->privates['Ibexa\\AdminUi\\EventListener\\SetViewParametersListener'])) {
            return $container->privates['Ibexa\\AdminUi\\EventListener\\SetViewParametersListener'];
        }
        $c = ($container->services['ibexa.api.repository'] ?? $container->getIbexa_Api_RepositoryService());

        if (isset($container->privates['Ibexa\\AdminUi\\EventListener\\SetViewParametersListener'])) {
            return $container->privates['Ibexa\\AdminUi\\EventListener\\SetViewParametersListener'];
        }
        $d = ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService());

        return $container->privates['Ibexa\\AdminUi\\EventListener\\SetViewParametersListener'] = new \Ibexa\AdminUi\EventListener\SetViewParametersListener($a, $b, $c, $d, new \Ibexa\AdminUi\Form\Provider\GroupedNonMetaFormFieldsProvider(($container->privates['Ibexa\\ContentForms\\Content\\Form\\Provider\\GroupedContentFormFieldsProvider'] ?? $container->load('getGroupedContentFormFieldsProviderService')), $d));
    }
}
