<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchLocationLoaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\GraphQL\DataLoader\SearchLocationLoader' shared autowired service.
     *
     * @return \Ibexa\GraphQL\DataLoader\SearchLocationLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/graphql/src/lib/DataLoader/LocationLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/graphql/src/lib/DataLoader/SearchLocationLoader.php';

        return $container->privates['Ibexa\\GraphQL\\DataLoader\\SearchLocationLoader'] = new \Ibexa\GraphQL\DataLoader\SearchLocationLoader(($container->services['ibexa.api.service.search'] ?? $container->getIbexa_Api_Service_SearchService()), ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService()), ($container->services['ibexa.api.service.url_alias'] ?? $container->getIbexa_Api_Service_UrlAliasService()), ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()), ($container->privates['Ibexa\\Core\\MVC\\Symfony\\Routing\\Generator\\UrlAliasGenerator'] ?? $container->getUrlAliasGeneratorService()));
    }
}
