<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSegmentGroupLimitationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Segmentation\Permission\Limitation\SegmentGroupLimitationType' shared autowired service.
     *
     * @return \Ibexa\Segmentation\Permission\Limitation\SegmentGroupLimitationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/contracts/Limitation/Type.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/segmentation/src/lib/Permission/Limitation/SegmentGroupLimitationType.php';

        return $container->privates['Ibexa\\Segmentation\\Permission\\Limitation\\SegmentGroupLimitationType'] = new \Ibexa\Segmentation\Permission\Limitation\SegmentGroupLimitationType(($container->privates['Ibexa\\Segmentation\\Persistence\\Handler\\DatabaseHandler'] ?? $container->getDatabaseHandlerService()));
    }
}
