<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Rest\Server\Controller\SessionController' shared autowired service.
     *
     * @return \Ibexa\Rest\Server\Controller\SessionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/rest/src/lib/Server/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/rest/src/lib/Server/Controller/SessionController.php';

        $a = ($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService());

        if (isset($container->services['Ibexa\\Rest\\Server\\Controller\\SessionController'])) {
            return $container->services['Ibexa\\Rest\\Server\\Controller\\SessionController'];
        }
        $b = ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService());

        if (isset($container->services['Ibexa\\Rest\\Server\\Controller\\SessionController'])) {
            return $container->services['Ibexa\\Rest\\Server\\Controller\\SessionController'];
        }
        $c = ($container->privates['ibexa.rest.security.authentication.listener.session.ibexa_front'] ?? $container->load('getIbexa_Rest_Security_Authentication_Listener_Session_IbexaFrontService'));

        if (isset($container->services['Ibexa\\Rest\\Server\\Controller\\SessionController'])) {
            return $container->services['Ibexa\\Rest\\Server\\Controller\\SessionController'];
        }

        $container->services['Ibexa\\Rest\\Server\\Controller\\SessionController'] = $instance = new \Ibexa\Rest\Server\Controller\SessionController('authenticate', $a, $b, $c, ($container->privates['Ibexa\\Rest\\Server\\Security\\CsrfTokenManager'] ?? $container->getCsrfTokenManagerService()), ($container->privates['security.csrf.token_storage'] ?? $container->getSecurity_Csrf_TokenStorageService()));

        $instance->setContainer($container);
        $instance->setInputDispatcher(($container->privates['Ibexa\\Rest\\Input\\Dispatcher'] ?? $container->getDispatcherService()));
        $instance->setRouter(($container->services['router'] ?? $container->getRouterService()));
        $instance->setRequestParser(($container->privates['Ibexa\\Bundle\\Rest\\RequestParser\\Router'] ?? $container->getRouter2Service()));
        $instance->setRepository(($container->services['ibexa.api.repository'] ?? $container->getIbexa_Api_RepositoryService()));

        return $instance;
    }
}
