<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubmissionsTabSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\FormBuilder\Tab\Event\Subscriber\SubmissionsTabSubscriber' shared autowired service.
     *
     * @return \Ibexa\FormBuilder\Tab\Event\Subscriber\SubmissionsTabSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/form-builder/src/lib/Tab/Event/Subscriber/SubmissionsTabSubscriber.php';

        return $container->privates['Ibexa\\FormBuilder\\Tab\\Event\\Subscriber\\SubmissionsTabSubscriber'] = new \Ibexa\FormBuilder\Tab\Event\Subscriber\SubmissionsTabSubscriber(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
