<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityListener2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\PageBuilder\Security\EventListener\SecurityListener' shared autowired service.
     *
     * @return \Ibexa\PageBuilder\Security\EventListener\SecurityListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/page-builder/src/lib/Security/EventListener/SecurityListener.php';

        $a = ($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService());

        if (isset($container->privates['Ibexa\\PageBuilder\\Security\\EventListener\\SecurityListener'])) {
            return $container->privates['Ibexa\\PageBuilder\\Security\\EventListener\\SecurityListener'];
        }

        return $container->privates['Ibexa\\PageBuilder\\Security\\EventListener\\SecurityListener'] = new \Ibexa\PageBuilder\Security\EventListener\SecurityListener($a);
    }
}
