<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSectionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\AdminUi\Controller\SectionController' shared autowired service.
     *
     * @return \Ibexa\Bundle\AdminUi\Controller\SectionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/bundle/Controller/SectionController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Form/DataMapper/DataMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Form/DataMapper/SectionCreateMapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Form/DataMapper/SectionUpdateMapper.php';

        $container->services['Ibexa\\Bundle\\AdminUi\\Controller\\SectionController'] = $instance = new \Ibexa\Bundle\AdminUi\Controller\SectionController(($container->privates['Ibexa\\AdminUi\\Notification\\TranslatableNotificationHandler'] ?? $container->getTranslatableNotificationHandlerService()), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()), ($container->services['ibexa.api.service.section'] ?? $container->getIbexa_Api_Service_SectionService()), ($container->services['ibexa.api.service.search'] ?? $container->getIbexa_Api_Service_SearchService()), ($container->privates['Ibexa\\AdminUi\\Form\\Factory\\FormFactory'] ?? $container->getFormFactory2Service()), new \Ibexa\AdminUi\Form\DataMapper\SectionCreateMapper(), new \Ibexa\AdminUi\Form\DataMapper\SectionUpdateMapper(), ($container->privates['Ibexa\\AdminUi\\Form\\SubmitHandler'] ?? $container->load('getSubmitHandlerService')), ($container->services['ibexa.api.service.location'] ?? $container->getIbexa_Api_Service_LocationService()), ($container->privates['Ibexa\\AdminUi\\UI\\Service\\PathService'] ?? $container->load('getPathServiceService')), ($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService()), ($container->privates['Ibexa\\AdminUi\\Permission\\PermissionChecker'] ?? $container->load('getPermissionCheckerService')), ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()));

        $instance->setContainer($container);
        $instance->performAccessCheck();

        return $instance;
    }
}
