<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSingleMeasurementAssetTagsStorageConverterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Measurement\ProductCatalog\Local\AssetTags\SingleMeasurementAssetTagsStorageConverter' shared autowired service.
     *
     * @return \Ibexa\Measurement\ProductCatalog\Local\AssetTags\SingleMeasurementAssetTagsStorageConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/lib/Local/Repository/AssetTags/AssetTagsStorageConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/measurement/src/lib/ProductCatalog/Local/AssetTags/SingleMeasurementAssetTagsStorageConverter.php';

        return $container->privates['Ibexa\\Measurement\\ProductCatalog\\Local\\AssetTags\\SingleMeasurementAssetTagsStorageConverter'] = new \Ibexa\Measurement\ProductCatalog\Local\AssetTags\SingleMeasurementAssetTagsStorageConverter(($container->privates['Ibexa\\Measurement\\ProductCatalog\\Local\\Attribute\\SingleMeasurementStorageConverter'] ?? $container->load('getSingleMeasurementStorageConverterService')), ($container->privates['Ibexa\\Measurement\\MeasurementService'] ?? $container->getMeasurementServiceService()));
    }
}
