<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Overblog\GraphQLBundle\Definition\Builder\TypeFactory' shared service.
     *
     * @return \Overblog\GraphQLBundle\Definition\Builder\TypeFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/Builder/TypeFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/ConfigProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/GraphQLServices.php';

        return $container->privates['Overblog\\GraphQLBundle\\Definition\\Builder\\TypeFactory'] = new \Overblog\GraphQLBundle\Definition\Builder\TypeFactory(new \Overblog\GraphQLBundle\Definition\ConfigProcessor(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Overblog\\GraphQLBundle\\Definition\\ConfigProcessor\\PublicFieldsFilterConfigProcessor'] ?? ($container->privates['Overblog\\GraphQLBundle\\Definition\\ConfigProcessor\\PublicFieldsFilterConfigProcessor'] = new \Overblog\GraphQLBundle\Definition\ConfigProcessor\PublicFieldsFilterConfigProcessor()));
            yield 1 => ($container->privates['Overblog\\GraphQLBundle\\Definition\\ConfigProcessor\\AclConfigProcessor'] ?? $container->load('getAclConfigProcessorService'));
            yield 2 => ($container->privates['Overblog\\GraphQLBundle\\Definition\\ConfigProcessor\\WrapArgumentConfigProcessor'] ?? $container->load('getWrapArgumentConfigProcessorService'));
        }, 3)), new \Overblog\GraphQLBundle\Definition\GraphQLServices(['argumentFactory' => function () use ($container) {
            return ($container->privates['Overblog\\GraphQLBundle\\Definition\\ArgumentFactory'] ?? ($container->privates['Overblog\\GraphQLBundle\\Definition\\ArgumentFactory'] = new \Overblog\GraphQLBundle\Definition\ArgumentFactory('Overblog\\GraphQLBundle\\Definition\\Argument')));
        }, 'container' => function () use ($container) {
            return $container;
        }, 'input_validator_factory' => function () use ($container) {
            return ($container->privates['Overblog\\GraphQLBundle\\Validator\\InputValidatorFactory'] ?? $container->load('getInputValidatorFactoryService'));
        }, 'mutationResolver' => function () use ($container) {
            return ($container->services['overblog_graphql.mutation_resolver'] ?? $container->load('getOverblogGraphql_MutationResolverService'));
        }, 'queryResolver' => function () use ($container) {
            return ($container->services['overblog_graphql.query_resolver'] ?? $container->load('getOverblogGraphql_QueryResolverService'));
        }, 'security' => function () use ($container) {
            return ($container->privates['Overblog\\GraphQLBundle\\Security\\Security'] ?? $container->load('getSecurityService'));
        }, 'typeResolver' => function () use ($container) {
            return ($container->services['overblog_graphql.type_resolver'] ?? $container->load('getOverblogGraphql_TypeResolverService'));
        }]));
    }
}
