<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxonomyEntryFieldTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Taxonomy\Form\Type\TaxonomyEntryFieldType' shared autowired service.
     *
     * @return \Ibexa\Taxonomy\Form\Type\TaxonomyEntryFieldType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/taxonomy/src/lib/Form/Type/TaxonomyEntryFieldType.php';

        $a = ($container->privates['Ibexa\\Taxonomy\\Service\\Event\\TaxonomyService'] ?? $container->getTaxonomyServiceService());

        if (isset($container->privates['Ibexa\\Taxonomy\\Form\\Type\\TaxonomyEntryFieldType'])) {
            return $container->privates['Ibexa\\Taxonomy\\Form\\Type\\TaxonomyEntryFieldType'];
        }

        return $container->privates['Ibexa\\Taxonomy\\Form\\Type\\TaxonomyEntryFieldType'] = new \Ibexa\Taxonomy\Form\Type\TaxonomyEntryFieldType($a);
    }
}
