<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxonomyEntryAssignmentFormMapperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Taxonomy\FieldType\TaxonomyEntryAssignment\FormMapper\TaxonomyEntryAssignmentFormMapper' shared autowired service.
     *
     * @return \Ibexa\Taxonomy\FieldType\TaxonomyEntryAssignment\FormMapper\TaxonomyEntryAssignmentFormMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/contracts/FieldType/FieldValueFormMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/FieldType/FieldDefinitionFormMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/taxonomy/src/lib/FieldType/TaxonomyEntryAssignment/FormMapper/TaxonomyEntryAssignmentFormMapper.php';

        $a = ($container->privates['Ibexa\\Core\\Repository\\Permission\\CachedPermissionService'] ?? $container->getCachedPermissionServiceService());

        if (isset($container->privates['Ibexa\\Taxonomy\\FieldType\\TaxonomyEntryAssignment\\FormMapper\\TaxonomyEntryAssignmentFormMapper'])) {
            return $container->privates['Ibexa\\Taxonomy\\FieldType\\TaxonomyEntryAssignment\\FormMapper\\TaxonomyEntryAssignmentFormMapper'];
        }

        return $container->privates['Ibexa\\Taxonomy\\FieldType\\TaxonomyEntryAssignment\\FormMapper\\TaxonomyEntryAssignmentFormMapper'] = new \Ibexa\Taxonomy\FieldType\TaxonomyEntryAssignment\FormMapper\TaxonomyEntryAssignmentFormMapper($a);
    }
}
