<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxonomyEntryAssignmentIdentifierConverterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Taxonomy\Event\Subscriber\FieldType\TaxonomyEntryAssignmentIdentifierConverter' shared autowired service.
     *
     * @return \Ibexa\Taxonomy\Event\Subscriber\FieldType\TaxonomyEntryAssignmentIdentifierConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/taxonomy/src/lib/Event/Subscriber/FieldType/TaxonomyEntryAssignmentIdentifierConverter.php';

        $a = ($container->privates['Ibexa\\Taxonomy\\Service\\Event\\TaxonomyService'] ?? $container->getTaxonomyServiceService());

        if (isset($container->privates['Ibexa\\Taxonomy\\Event\\Subscriber\\FieldType\\TaxonomyEntryAssignmentIdentifierConverter'])) {
            return $container->privates['Ibexa\\Taxonomy\\Event\\Subscriber\\FieldType\\TaxonomyEntryAssignmentIdentifierConverter'];
        }

        return $container->privates['Ibexa\\Taxonomy\\Event\\Subscriber\\FieldType\\TaxonomyEntryAssignmentIdentifierConverter'] = new \Ibexa\Taxonomy\Event\Subscriber\FieldType\TaxonomyEntryAssignmentIdentifierConverter('ibexa_taxonomy_entry_assignment', $a);
    }
}
