<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxonomyEntryAssignmentFieldTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Taxonomy\Form\Type\TaxonomyEntryAssignmentFieldType' shared autowired service.
     *
     * @return \Ibexa\Taxonomy\Form\Type\TaxonomyEntryAssignmentFieldType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/taxonomy/src/lib/Form/Type/TaxonomyEntryAssignmentFieldType.php';

        return $container->privates['Ibexa\\Taxonomy\\Form\\Type\\TaxonomyEntryAssignmentFieldType'] = new \Ibexa\Taxonomy\Form\Type\TaxonomyEntryAssignmentFieldType();
    }
}
