<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxonomyResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Taxonomy\GraphQL\Resolver\TaxonomyResolver' shared autowired service.
     *
     * @return \Ibexa\Taxonomy\GraphQL\Resolver\TaxonomyResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/Resolver/QueryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/taxonomy/src/lib/GraphQL/Resolver/TaxonomyResolver.php';

        return $container->privates['Ibexa\\Taxonomy\\GraphQL\\Resolver\\TaxonomyResolver'] = new \Ibexa\Taxonomy\GraphQL\Resolver\TaxonomyResolver(($container->privates['Ibexa\\Taxonomy\\Tree\\TaxonomyTreeService'] ?? $container->load('getTaxonomyTreeServiceService')), ($container->privates['Ibexa\\Taxonomy\\Service\\Event\\TaxonomyService'] ?? $container->getTaxonomyServiceService()), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()));
    }
}
