<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getURLWildcardEditRightSidebarBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\AdminUi\Menu\URLWildcardEditRightSidebarBuilder' shared autowired service.
     *
     * @return \Ibexa\AdminUi\Menu\URLWildcardEditRightSidebarBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Menu/AbstractBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Menu/URLWildcardEditRightSidebarBuilder.php';

        $a = ($container->services['Ibexa\\AdminUi\\Menu\\MenuItemFactory'] ?? $container->load('getMenuItemFactoryService'));

        if (isset($container->services['Ibexa\\AdminUi\\Menu\\URLWildcardEditRightSidebarBuilder'])) {
            return $container->services['Ibexa\\AdminUi\\Menu\\URLWildcardEditRightSidebarBuilder'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['Ibexa\\AdminUi\\Menu\\URLWildcardEditRightSidebarBuilder'])) {
            return $container->services['Ibexa\\AdminUi\\Menu\\URLWildcardEditRightSidebarBuilder'];
        }

        return $container->services['Ibexa\\AdminUi\\Menu\\URLWildcardEditRightSidebarBuilder'] = new \Ibexa\AdminUi\Menu\URLWildcardEditRightSidebarBuilder($a, $b, ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()));
    }
}
