<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUniversalDiscoveryRequestQueryArgumentResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.Ibexa\Bundle\AdminUi\ControllerArgumentResolver\UniversalDiscoveryRequestQueryArgumentResolver' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/bundle/ControllerArgumentResolver/UniversalDiscoveryRequestQueryArgumentResolver.php';

        $a = ($container->privates['Ibexa\\AdminUi\\UniversalDiscovery\\UniversalDiscoveryProvider'] ?? $container->load('getUniversalDiscoveryProviderService'));

        if (isset($container->privates['debug.Ibexa\\Bundle\\AdminUi\\ControllerArgumentResolver\\UniversalDiscoveryRequestQueryArgumentResolver'])) {
            return $container->privates['debug.Ibexa\\Bundle\\AdminUi\\ControllerArgumentResolver\\UniversalDiscoveryRequestQueryArgumentResolver'];
        }
        $b = ($container->services['.container.private.validator'] ?? $container->get_Container_Private_ValidatorService());

        if (isset($container->privates['debug.Ibexa\\Bundle\\AdminUi\\ControllerArgumentResolver\\UniversalDiscoveryRequestQueryArgumentResolver'])) {
            return $container->privates['debug.Ibexa\\Bundle\\AdminUi\\ControllerArgumentResolver\\UniversalDiscoveryRequestQueryArgumentResolver'];
        }

        return $container->privates['debug.Ibexa\\Bundle\\AdminUi\\ControllerArgumentResolver\\UniversalDiscoveryRequestQueryArgumentResolver'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Ibexa\Bundle\AdminUi\ControllerArgumentResolver\UniversalDiscoveryRequestQueryArgumentResolver($a, $b), ($container->privates['debug.stopwatch'] ?? ($container->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
    }
}
