<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnassignFromUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Segmentation\StepExecutor\ActionExecutor\Segment\UnassignFromUser' shared autowired service.
     *
     * @return \Ibexa\Segmentation\StepExecutor\ActionExecutor\Segment\UnassignFromUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ActionExecutor/ExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/segmentation/src/lib/StepExecutor/ActionExecutor/AbstractAssignToUser.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/segmentation/src/lib/StepExecutor/ActionExecutor/Segment/UnassignFromUser.php';

        return $container->privates['Ibexa\\Segmentation\\StepExecutor\\ActionExecutor\\Segment\\UnassignFromUser'] = new \Ibexa\Segmentation\StepExecutor\ActionExecutor\Segment\UnassignFromUser(($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService()), ($container->privates['Ibexa\\Segmentation\\Service\\Event\\SegmentationServiceEventDecorator'] ?? $container->getSegmentationServiceEventDecoratorService()));
    }
}
