<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateController7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\ProductCatalog\Controller\Product\Availability\UpdateController' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Controller\Product\Availability\UpdateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Controller/Product/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Controller/Product/Availability/UpdateController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Form/DataMapper/ProductAvailabilityUpdateMapper.php';

        $container->services['Ibexa\\Bundle\\ProductCatalog\\Controller\\Product\\Availability\\UpdateController'] = $instance = new \Ibexa\Bundle\ProductCatalog\Controller\Product\Availability\UpdateController(($container->privates['Ibexa\\AdminUi\\Notification\\TranslatableNotificationHandler'] ?? $container->getTranslatableNotificationHandlerService()), ($container->privates['Ibexa\\AdminUi\\Form\\SubmitHandler'] ?? $container->load('getSubmitHandlerService')), ($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\Event\\ProductAvailabilityService'] ?? $container->getProductAvailabilityServiceService()), new \Ibexa\Bundle\ProductCatalog\Form\DataMapper\ProductAvailabilityUpdateMapper(), ($container->privates['Ibexa\\Core\\Repository\\Repository'] ?? $container->getRepositoryService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Ibexa\\Bundle\\ProductCatalog\\Controller\\Product\\Availability\\UpdateController', $container));

        return $instance;
    }
}
