<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserUpdateFormProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\ContentForms\Form\Processor\User\UserUpdateFormProcessor' shared service.
     *
     * @return \Ibexa\ContentForms\Form\Processor\User\UserUpdateFormProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/content-forms/src/lib/Form/Processor/User/UserUpdateFormProcessor.php';

        $a = ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService());

        if (isset($container->privates['Ibexa\\ContentForms\\Form\\Processor\\User\\UserUpdateFormProcessor'])) {
            return $container->privates['Ibexa\\ContentForms\\Form\\Processor\\User\\UserUpdateFormProcessor'];
        }
        $b = ($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService());

        if (isset($container->privates['Ibexa\\ContentForms\\Form\\Processor\\User\\UserUpdateFormProcessor'])) {
            return $container->privates['Ibexa\\ContentForms\\Form\\Processor\\User\\UserUpdateFormProcessor'];
        }
        $c = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['Ibexa\\ContentForms\\Form\\Processor\\User\\UserUpdateFormProcessor'])) {
            return $container->privates['Ibexa\\ContentForms\\Form\\Processor\\User\\UserUpdateFormProcessor'];
        }

        return $container->privates['Ibexa\\ContentForms\\Form\\Processor\\User\\UserUpdateFormProcessor'] = new \Ibexa\ContentForms\Form\Processor\User\UserUpdateFormProcessor($a, $b, $c);
    }
}
