<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnassignGroupExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Migration\StepExecutor\ActionExecutor\ContentType\Update\UnassignGroupExecutor' shared autowired service.
     *
     * @return \Ibexa\Migration\StepExecutor\ActionExecutor\ContentType\Update\UnassignGroupExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ActionExecutor/ExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/migrations/src/lib/StepExecutor/ActionExecutor/ContentType/Update/UnassignGroupExecutor.php';

        return $container->privates['Ibexa\\Migration\\StepExecutor\\ActionExecutor\\ContentType\\Update\\UnassignGroupExecutor'] = new \Ibexa\Migration\StepExecutor\ActionExecutor\ContentType\Update\UnassignGroupExecutor(($container->services['ibexa.api.service.content_type'] ?? $container->getIbexa_Api_Service_ContentTypeService()));
    }
}
