<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUniqueURLValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\AdminUi\Validator\Constraints\UniqueURLValidator' shared autowired service.
     *
     * @return \Ibexa\AdminUi\Validator\Constraints\UniqueURLValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/lib/Validator/Constraints/UniqueURLValidator.php';

        $a = ($container->services['ibexa.api.service.url'] ?? $container->getIbexa_Api_Service_UrlService());

        if (isset($container->privates['Ibexa\\AdminUi\\Validator\\Constraints\\UniqueURLValidator'])) {
            return $container->privates['Ibexa\\AdminUi\\Validator\\Constraints\\UniqueURLValidator'];
        }

        return $container->privates['Ibexa\\AdminUi\\Validator\\Constraints\\UniqueURLValidator'] = new \Ibexa\AdminUi\Validator\Constraints\UniqueURLValidator($a);
    }
}
