<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPasswordValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\User\Validator\Constraints\UserPasswordValidator' shared autowired service.
     *
     * @return \Ibexa\User\Validator\Constraints\UserPasswordValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/user/src/lib/Validator/Constraints/UserPasswordValidator.php';

        $a = ($container->services['ibexa.api.service.user'] ?? $container->getIbexa_Api_Service_UserService());

        if (isset($container->privates['Ibexa\\User\\Validator\\Constraints\\UserPasswordValidator'])) {
            return $container->privates['Ibexa\\User\\Validator\\Constraints\\UserPasswordValidator'];
        }

        return $container->privates['Ibexa\\User\\Validator\\Constraints\\UserPasswordValidator'] = new \Ibexa\User\Validator\Constraints\UserPasswordValidator($a, ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
