<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUniqueScenarioReferenceCodeValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Personalization\Validator\Constraints\UniqueScenarioReferenceCodeValidator' shared autowired service.
     *
     * @return \Ibexa\Personalization\Validator\Constraints\UniqueScenarioReferenceCodeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/personalization/src/lib/Validator/Constraints/UniqueScenarioReferenceCodeValidator.php';

        $a = ($container->privates['Ibexa\\Personalization\\Cache\\CachedScenarioService'] ?? $container->load('getCachedScenarioServiceService'));

        if (isset($container->privates['Ibexa\\Personalization\\Validator\\Constraints\\UniqueScenarioReferenceCodeValidator'])) {
            return $container->privates['Ibexa\\Personalization\\Validator\\Constraints\\UniqueScenarioReferenceCodeValidator'];
        }

        return $container->privates['Ibexa\\Personalization\\Validator\\Constraints\\UniqueScenarioReferenceCodeValidator'] = new \Ibexa\Personalization\Validator\Constraints\UniqueScenarioReferenceCodeValidator($a);
    }
}
