<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Ibexa\Bundle\ProductCatalog\Controller\AttributeGroup\UpdateController' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Controller\AttributeGroup\UpdateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/admin-ui/src/contracts/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Controller/AttributeGroup/UpdateController.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Form/FormMapper/AttributeGroupMapper.php';

        $container->services['Ibexa\\Bundle\\ProductCatalog\\Controller\\AttributeGroup\\UpdateController'] = $instance = new \Ibexa\Bundle\ProductCatalog\Controller\AttributeGroup\UpdateController(($container->privates['Ibexa\\ProductCatalog\\Local\\Repository\\Event\\AttributeGroupService'] ?? $container->load('getAttributeGroupServiceService')), ($container->privates['Ibexa\\AdminUi\\Form\\SubmitHandler'] ?? $container->load('getSubmitHandlerService')), ($container->privates['Ibexa\\AdminUi\\Notification\\TranslatableNotificationHandler'] ?? $container->getTranslatableNotificationHandlerService()), new \Ibexa\Bundle\ProductCatalog\Form\FormMapper\AttributeGroupMapper(($container->privates['Ibexa\\ProductCatalog\\Dispatcher\\AttributeGroupServiceDispatcher'] ?? $container->getAttributeGroupServiceDispatcherService())), ($container->services['ibexa.api.service.language'] ?? $container->getIbexa_Api_Service_LanguageService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Ibexa\\Bundle\\ProductCatalog\\Controller\\AttributeGroup\\UpdateController', $container));

        return $instance;
    }
}
