<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUniqueProductCodeValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\ProductCatalog\Validator\Constraints\UniqueProductCodeValidator' shared autowired service.
     *
     * @return \Ibexa\Bundle\ProductCatalog\Validator\Constraints\UniqueProductCodeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/product-catalog/src/bundle/Validator/Constraints/UniqueProductCodeValidator.php';

        $a = ($container->privates['Ibexa\\ProductCatalog\\Dispatcher\\ProductServiceDispatcher'] ?? $container->getProductServiceDispatcherService());

        if (isset($container->privates['Ibexa\\Bundle\\ProductCatalog\\Validator\\Constraints\\UniqueProductCodeValidator'])) {
            return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Validator\\Constraints\\UniqueProductCodeValidator'];
        }

        return $container->privates['Ibexa\\Bundle\\ProductCatalog\\Validator\\Constraints\\UniqueProductCodeValidator'] = new \Ibexa\Bundle\ProductCatalog\Validator\Constraints\UniqueProductCodeValidator($a);
    }
}
