<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewbaseLayoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Core\MVC\Symfony\View\ParametersInjector\ViewbaseLayout' shared service.
     *
     * @return \Ibexa\Core\MVC\Symfony\View\ParametersInjector\ViewbaseLayout
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/lib/MVC/Symfony/View/ParametersInjector/ViewbaseLayout.php';

        return $container->privates['Ibexa\\Core\\MVC\\Symfony\\View\\ParametersInjector\\ViewbaseLayout'] = new \Ibexa\Core\MVC\Symfony\View\ParametersInjector\ViewbaseLayout('@IbexaCore/viewbase_layout.html.twig', ($container->services['Ibexa\\Bundle\\Core\\DependencyInjection\\Configuration\\ChainConfigResolver'] ?? $container->getChainConfigResolverService()));
    }
}
