<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVersionLockedExceptionListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Workflow\Event\Subscriber\VersionLockedExceptionListener' shared autowired service.
     *
     * @return \Ibexa\Workflow\Event\Subscriber\VersionLockedExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/workflow/src/lib/Event/Subscriber/VersionLockedExceptionListener.php';

        $a = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['Ibexa\\Workflow\\Event\\Subscriber\\VersionLockedExceptionListener'])) {
            return $container->privates['Ibexa\\Workflow\\Event\\Subscriber\\VersionLockedExceptionListener'];
        }
        $b = ($container->services['ibexa.api.service.content'] ?? $container->getIbexa_Api_Service_ContentService());

        if (isset($container->privates['Ibexa\\Workflow\\Event\\Subscriber\\VersionLockedExceptionListener'])) {
            return $container->privates['Ibexa\\Workflow\\Event\\Subscriber\\VersionLockedExceptionListener'];
        }

        return $container->privates['Ibexa\\Workflow\\Event\\Subscriber\\VersionLockedExceptionListener'] = new \Ibexa\Workflow\Event\Subscriber\VersionLockedExceptionListener($a, $b, ($container->privates['Ibexa\\AdminUi\\Notification\\TranslatableNotificationHandler'] ?? $container->getTranslatableNotificationHandlerService()));
    }
}
