<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewRendererListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Bundle\Core\EventListener\ViewRendererListener' shared service.
     *
     * @return \Ibexa\Bundle\Core\EventListener\ViewRendererListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/core/src/bundle/Core/EventListener/ViewRendererListener.php';

        $a = ($container->privates['Ibexa\\Core\\MVC\\Symfony\\View\\Renderer\\TemplateRenderer'] ?? $container->load('getTemplateRendererService'));

        if (isset($container->privates['Ibexa\\Bundle\\Core\\EventListener\\ViewRendererListener'])) {
            return $container->privates['Ibexa\\Bundle\\Core\\EventListener\\ViewRendererListener'];
        }

        return $container->privates['Ibexa\\Bundle\\Core\\EventListener\\ViewRendererListener'] = new \Ibexa\Bundle\Core\EventListener\ViewRendererListener($a);
    }
}
