<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVersionsCountMetricsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\SystemInfo\Storage\Metrics\VersionsCountMetrics' shared service.
     *
     * @return \Ibexa\SystemInfo\Storage\Metrics\VersionsCountMetrics
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/Storage/Metrics.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/Storage/Metrics/RepositoryConnectionAwareMetrics.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/system-info/src/lib/Storage/Metrics/VersionsCountMetrics.php';

        return $container->privates['Ibexa\\SystemInfo\\Storage\\Metrics\\VersionsCountMetrics'] = new \Ibexa\SystemInfo\Storage\Metrics\VersionsCountMetrics(($container->services['ibexa.persistence.connection'] ?? $container->getIbexa_Persistence_ConnectionService()));
    }
}
