<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflowTransitionChoiceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Ibexa\Workflow\Form\Type\WorkflowTransitionChoiceType' shared autowired service.
     *
     * @return \Ibexa\Workflow\Form\Type\WorkflowTransitionChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/ibexa/workflow/src/lib/Form/Type/WorkflowTransitionChoiceType.php';

        $a = ($container->privates['Ibexa\\Workflow\\Registry\\WorkflowRegistry'] ?? $container->getWorkflowRegistryService());

        if (isset($container->privates['Ibexa\\Workflow\\Form\\Type\\WorkflowTransitionChoiceType'])) {
            return $container->privates['Ibexa\\Workflow\\Form\\Type\\WorkflowTransitionChoiceType'];
        }
        $b = ($container->privates['Ibexa\\Workflow\\Registry\\WorkflowDefinitionMetadataRegistry'] ?? $container->getWorkflowDefinitionMetadataRegistryService());

        if (isset($container->privates['Ibexa\\Workflow\\Form\\Type\\WorkflowTransitionChoiceType'])) {
            return $container->privates['Ibexa\\Workflow\\Form\\Type\\WorkflowTransitionChoiceType'];
        }

        return $container->privates['Ibexa\\Workflow\\Form\\Type\\WorkflowTransitionChoiceType'] = new \Ibexa\Workflow\Form\Type\WorkflowTransitionChoiceType($a, $b);
    }
}
