<?php

namespace Container2YcVERS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWrapArgumentConfigProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Overblog\GraphQLBundle\Definition\ConfigProcessor\WrapArgumentConfigProcessor' shared service.
     *
     * @return \Overblog\GraphQLBundle\Definition\ConfigProcessor\WrapArgumentConfigProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/ConfigProcessor/ConfigProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/ConfigProcessor/WrapArgumentConfigProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/ArgumentFactory.php';

        return $container->privates['Overblog\\GraphQLBundle\\Definition\\ConfigProcessor\\WrapArgumentConfigProcessor'] = new \Overblog\GraphQLBundle\Definition\ConfigProcessor\WrapArgumentConfigProcessor(($container->privates['Overblog\\GraphQLBundle\\Definition\\ArgumentFactory'] ?? ($container->privates['Overblog\\GraphQLBundle\\Definition\\ArgumentFactory'] = new \Overblog\GraphQLBundle\Definition\ArgumentFactory('Overblog\\GraphQLBundle\\Definition\\Argument'))));
    }
}
